### ISSUE TITLE
Programming ligatures

### ISSUE THREAD

**Issue by antanst** [be5invis/Iosevka#69] opened 2016-03-03 07:54 UTC
Since this typeface is marketed towards programming, perhaps some ligatures would be of interest, like in the Fira Code, Hasklig or PragmataPro fonts. Personally, I find Fira Code's ligature preferences the most correctly designed and pleasing to the eye.

**Comment by alexeyten** [comment] 2016-03-03 12:21
dup #56

**Comment by be5invis** [comment] 2016-03-04 14:44
Duplicate of #56 . Closed.

**Closed by be5invis** 2016-03-04 14:44 UTC
