### ISSUE TITLE
Add “original” glyph as FWID variant of U+212E ESTIMATED SYMBOL

### ISSUE THREAD

**Issue by dscorbett** [be5invis/Iosevka#507] opened 2020-04-22 13:45 UTC
* Your font version: 3.0.0-rc.7
* Your font variant: Iosevka Extended
* Your operating system (name and version): macOS 10.14.6
* Your application using Iosevka: hb-view

----

The glyph for U+212E ESTIMATED SYMBOL is a vertically stretched ⟨e⟩, but it is supposed to be [a specific symbol with certain proportions](https://upload.wikimedia.org/wikipedia/commons/3/3f/Estimated_sign_detail.svg). It may have to be condensed to fit Iosevka’s metrics, but even considering that constraint, the current glyph looks wrong.
![℮](https://user-images.githubusercontent.com/1124347/79989201-97c0e100-847d-11ea-86a3-a2e8fe003902.png)

**Comment by be5invis** [comment] 2020-04-22 22:26
This is considered by design for now. The “original” glyph could become a feature for post-3.0 as a “fwid” variant.

**Comment by be5invis** [comment] 2020-04-23 05:04
I'd like to make it like this for v3. This issue will be left open for adding the original one.
![image](https://user-images.githubusercontent.com/240091/80061089-1a30bb80-84e5-11ea-8b52-5785a39fc762.png)

**Comment by be5invis** [comment] 2020-04-23 05:05
@dscorbett Feel free to close this if you think it is "good enough".

**Comment by dscorbett** [comment] 2020-04-23 11:19
Do you mean that U+212E would get the middle glyph by default, without 'fwid'? If so, I think that is good enough.

**Closed** 2020-04-23 11:19 UTC
Labels: Backlog, Post 3.0, Variant Request

**Comment by dscorbett** [comment] 2020-04-24 12:17
@be5invis, shouldn’t this be mentioned in the 3.0.0-rc.8 release notes?
