### ISSUE TITLE
Wrong glyph for U+E0BA?

### ISSUE THREAD

**Issue by Ptival** [be5invis/Iosevka#421] opened 2020-02-09 13:12 UTC
* Your font version: iosevka-2.3.3 (github revision)
* Your font variant: SS05
* Your operating system (name and version): NixOS 20.03
* Your application using Iosevka: Terminator, gucharmap, seems pervasive enough

---

As far as I can tell, the Iosevka SS05 glyph `U+E0BA` seems to be incorrectly the same as `U+E0BE`:

![image](https://user-images.githubusercontent.com/478606/74102641-cb11f600-4b45-11ea-93f5-6e5b7c189aff.png)

(Note: `U+E0BE is the rightmost one on this screenshot, notice it is the same as the selected `U+E0BA)

Here is how the glyphs show up in every other font on my computer:

![image](https://user-images.githubusercontent.com/478606/74102649-e4b33d80-4b45-11ea-9b6e-d2601fccbacd.png)

This is more like what I expected.

**Comment by be5invis** [comment] 2020-02-09 23:57
Dupe of #379. Closed.
Current dev looks like this ↓
![image](https://user-images.githubusercontent.com/240091/74112851-dd476080-4b54-11ea-9c7e-74b0b29762d7.png)

**Closed by be5invis** 2020-02-09 23:57 UTC
