### ISSUE TITLE
Terminal letter-spacing error

### ISSUE THREAD

**Issue by liangjingkanji** [be5invis/Iosevka#635] opened 2020-07-17 13:03 UTC
between i - g, l - o, i - d. 
![image](https://user-images.githubusercontent.com/21078112/87786676-f2938a00-c86c-11ea-98de-e5b934609ad7.png)

![image](https://user-images.githubusercontent.com/21078112/87789012-ea3d4e00-c870-11ea-9beb-2a8a8ff1f422.png)

[Drake.terminal.zip](https://github.com/be5invis/Iosevka/files/4937940/Drake.terminal.zip)

Environment: Mac terminal
Font version:  `Iosevka sparkle v3.3.0`

**Comment by alexeyten** [comment] 2020-07-17 13:34
Iosevka Sparkle is *not* monospaced font.

**Comment by liangjingkanji** [comment] 2020-07-17 14:31
But iosevka is narrow, And ">="  not as good looking as JetBrains Mono.

**Comment by be5invis** [comment] 2020-07-17 18:59
@liangjingkanji You can try to use the extended families in Iosevka or create a custom build with wider shape. Closed as by design.

**Closed by be5invis** 2020-07-17 18:59 UTC
Labels: 🐞 Bug
