### ISSUE TITLE
Changes to APL Glyphs

### ISSUE THREAD

**Issue by PyGamer0** [be5invis/Iosevka#1200] opened 2021-08-22 09:15 UTC
**Is your feature request related to a problem? Please describe.**
Some APL specific glyphs are not pleasing to look at.

**Describe the solution you'd like**
Something similar to below.
![image](https://user-images.githubusercontent.com/64531844/130349458-02889be0-32cd-487f-8b8b-0fd7b9460ac5.png)
Note: Some glyphs are inaccurate as I made them in MS-Paint.

**Describe alternatives you've considered**
For U+2371 and U+2372: the tilde can be placed on top of the `∨`/`∧` rather than between (like APL385 Unicode)

**Additional context**

**Comment by abrudz** [comment] 2021-08-22 10:06
So really, the issue is just to connect glyphs that have tiny gaps between logical components?

**Comment by PyGamer0** [comment] 2021-08-22 10:09
@abrudz yes (and changing the comment)

**Comment by abrudz** [comment] 2021-08-22 12:26
> too elongated

[Supposedly](https://aplwiki.com/wiki/Quad_name), `⎕` has the golden ratio, and all other APL glyphs are derived from that. So e.g. `⍒` and `⍋` contain `∇` and `∆` which are the isosceles triangles that can be inscribed into `⎕`.

**Comment by ViniciusGiroto** [comment] 2021-08-22 12:53
> > too elongated
> 
> [Supposedly](https://aplwiki.com/wiki/Quad_name), `⎕` has the golden ratio, and all other APL glyphs are derived from that. So e.g. `⍒` and `⍋` contain `∇` and `∆` which are the isosceles triangles that can be inscribed into `⎕`.

At least for APL386 Unicode, the vertical bar in 
`⍒` and `⍋` is the same height as the quad, not the triangle. I suppose that's why it looks so elongated in Iosevka

**Comment by PyGamer0** [comment] 2021-08-22 13:00
> At least for APL386 Unicode, the vertical bar in
`⍒` and `⍋` is the same height as the quad, not the triangle. I suppose that's why it looks so elongated in Iosevka

Maybe the triangle could be squished a little?

**Comment by ViniciusGiroto** [comment] 2021-08-22 13:06
> > At least for APL386 Unicode, the vertical bar in
> `⍒` and `⍋` is the same height as the quad, not the triangle. I suppose that's why it looks so elongated in Iosevka
> 
> Maybe the triangle could be squished a little?

Or maybe an equilateral triangle as it is on nand and nor?

**Comment by be5invis** [comment] 2021-08-22 23:10
I am curious, can `U+2371` and `U+2372` really be drawn as a tilde over `∨` / `∧`?

**Comment by PyGamer0** [comment] 2021-08-23 04:13
> I am curious, can `U+2371` and `U+2372` really be drawn as a tilde above `∨` / `∧`?

I think if the `∨` / `∧` are made smaller, than the tilde might fit.

**Comment by be5invis** [comment] 2021-08-25 01:52
More questions:
 
 * Should we align `∆` and `∇` shapes in `⍢`, `⍋`, `⍒`, and `⍫` to the operators instead of uppercase letters? They currently look larger than other APL symbols.
 * Is the shape of the Lamp symbol (`⍝`) in APL385 really correct? Unicode spec shows the circle and the surrounding part should detach.

**Comment by ViniciusGiroto** [comment] 2021-08-25 03:45
> More questions:
>  
>  * Should we align `∆` and `∇` shapes in `⍢`, `⍋`, `⍒`, and `⍫` to the operators instead of uppercase letters? They currently look larger than other APL symbols.

I think so, given that a APL code is mostly symbols, it would be more consistent.

>  * Is the shape of the Lamp symbol (`⍝`) in APL385 really correct? Unicode spec shows the circle and the surrounding part should detach.

Dyalog uses APL385(or 6?) Unicode, so I presume that is the most "correct" font

**Comment by abrudz** [comment] 2021-08-25 07:50
APL385 is *not* authoritative. Complex glyphs where originally created by overstriking two simple glyphs. APL385 dispenses with the relationship between such composite glyphs and the base glyphs, and instead takes the freedom to raise the `~` in `⍲` and `⍫` and also stretch the `∩` in `⍝` for improved clarity.

Most representative of the original typefaces are APL2741 and SAX2, which are both derived from IBM type ball fonts (that's the reason they are so thin; the ink is expected to bleed into the paper) which did rely on overstriking:

![font samples](https://user-images.githubusercontent.com/10961427/130734354-f56ac7c3-9476-4d41-b160-f65679ad3e53.png)

Note how neither APL2741 nor SAX2 treats `∆` quite like an operator (small and centred), but only SAX2 extends it upwards to the full capital height. (In the early days, `∆` was often used as space in identifiers, much like `_` is used in today's "snake case".) However, in neither font do the del(ta)s extend as far up or down as the horizontal lines in `⎕`.

Also noticeable that the diameter of the shoe does match `∘` and not `○` so APL385's rendering of `⍝` is correct.

**Comment by be5invis** [comment] 2021-08-28 07:00
Closing as fixed. Version 10.1.1 will refine the design of various glyphs, as well as introduces a configurable option `apl-form` / OT tag `APLF`, that changes various symbols (`∆`, `∇`, `○`, `←`, `→`, `↑`, `↓`) to prioritize APL-harmonization.

**Closed** 2021-08-29 00:09 UTC
