### ISSUE TITLE
Thanks for amazing font!

### ISSUE THREAD

**Issue by svipas** [be5invis/Iosevka#739] opened 2020-11-16 17:41 UTC
Thanks @be5invis a lot for this amazing font. I suggest to create GitHub sponsors or Patreon or paypal.me. It would be an honor to support you for such beautiful font, I love the extended version and I’m using it in every IDE and terminal. Thanks again! 🤩

**Comment by be5invis** [comment] 2020-11-16 22:31
You are welcome, but this is a duplicate of #576. Closing.

**Closed by be5invis** 2020-11-16 22:31 UTC
