### ISSUE TITLE
Do not build glyphs for excluded codepoints

### ISSUE THREAD

**Issue by alexeyten** [be5invis/Iosevka#607] opened 2020-06-18 06:43 UTC
If I understand correctly, even with this config
```toml
[buildPlans.iosevka-custom.exclude-chars]
ranges = [[128, 1114111]]
```
build process generates all the glyphs and then remove excluded at the gc stage.

Is it possible not to build them at all, cause it is the most time consuming step?

**Comment by be5invis** [comment] 2020-06-18 07:22
Duplicate of #602. Closed.

**Closed by be5invis** 2020-06-18 07:22 UTC

**Comment by alexeyten** [comment] 2020-06-18 09:52
I'm not sure if it's a duplicate.
That issue was about removing glyphs from final font file.
And this is about not generate them at all.

**Comment by alexeyten** [comment] 2020-06-18 10:02
Got it.

Thank you for a great font :smiley:
