### ISSUE TITLE
Skipping OpenType tags to reserve letters and numbers

### ISSUE THREAD

**Issue by AlsoScratch** [be5invis/Iosevka#725] opened 2020-11-12 10:23 UTC
As an example, there is currently no variants for capital `C`.

Thus, if there were to be one now, it would appear out of order from the rest of the letters in the README, should it take the next available tag.

So I’m wondering if you are considering skipping OpenType tags for letters and numbers to reserve them for future use.

I understand that this is more of an aesthetic issue but it would still be worth considering.

**Comment by be5invis** [comment] 2020-11-12 12:00
This might be an interesting idea, since we are still in alpha stage.

**Comment by be5invis** [comment] 2020-11-12 12:02
But, some selectors are applied to _shape forms_ instead of _letters_, for example, `cv01` applies to all the turn-v shapes, including `A`, `Λ` and `Δ`. So, splitting them will waste more tags, but has very limited benefit.

**Comment by AlsoScratch** [comment] 2020-11-12 12:47
You don't have to split any tags; you just have to reassign them:
- `cv01` for `A`
- `cv02` for `B`
- `cv03` for `C`
...
- `cv26` for `Z`
- `cv27` for `a`
- `cv28` for `b`
- `cv29` for `c`
...

Though it is true that:
- For `V`/`v`, only one of `cv22` and `cv48` would be used
- For `X`/`x`, only one of `cv24` and `cv50` would be used

**Comment by be5invis** [comment] 2020-11-12 13:05
@AlsoScratch Still I do not sink reserving tags for letters currently doesn't have any variants is a good idea, and no other font did this. Reordering tags is helpful, but it could only be done within major upgrade timeframe. Please note that, reassigning tags **is breaking change**, the "beautifulness" of the README is **much less important** than functional compatibility.

**Comment by AlsoScratch** [comment] 2020-11-12 15:19
To clarify: although we're still in the pre-RC stage, you don't think my justification to "reserve" OpenType tags is strong enough. Am I right to say that?

**Comment by be5invis** [comment] 2020-11-12 15:26
@AlsoScratch The problem is, no other fonts are reserving tags, and since you already suggested sharing tags for `Vv`, `Xx` and `Zz` (and perhaps `Cc`, `Ss`, ...), reserving one tag for each letter does not make too much sense.

**Comment by AlsoScratch** [comment] 2020-11-12 15:54
At the moment, how will you display the variants in the README and on the website?
- In alphabetical and numerical order (variants for `A` first, then `B`, then `C`, etc.) even if the tags are not in order
or
- In `cv##` tag order?

**Comment by be5invis** [comment] 2020-11-12 17:09
@AlsoScratch Alphabetical. In this order: Capital Latin → Lower Latin → Non-Latin letters → Numbers → Symbols.

**Comment by be5invis** [comment] 2020-12-03 08:34
Closing, as 4.0 has been released.

**Closed by be5invis** 2020-12-03 08:34 UTC
Labels: ＊ Needs Justification, 🖋 OpenType
