### ISSUE TITLE
OpenType specification and weights

### ISSUE THREAD

**Issue by Diablo-D3** [be5invis/Iosevka#979] opened 2021-05-03 05:44 UTC
Iosevka is an amazing font that has almost every weight one could possibly ask for...

However, the specification (as [DirectWrite documents](https://docs.microsoft.com/en-us/windows/win32/api/dwrite/ne-dwrite-dwrite_font_weight)) recognizes, by name, two additional weights: 350 and 950, aliased as Semi-Light and Ultra-/Extra-black, respectively.

Given the never-ending fight against getting fonts to render Just Right&tm; in a wide range of text editors, 350 would be valuable for users that use 300 or 400 as their standard weight, just to nudge it just a little bit in the right direction.

**Comment by be5invis** [comment] 2021-05-03 06:15
These are not included in CSS' standard weights, so I decided to not include them in prebuilts. If you like, you can create a custom build with something like:
```toml
[buildPlans.iosevka-custom.weights.regular]
shape = 350
menu  = 400
css   = 400
```
Closing as by design.

**Closed by be5invis** 2021-05-03 06:15 UTC

**Comment by be5invis** [comment] 2021-05-03 06:16
Also, DWrite's document **is NOT OpenType Spec**. It is the document of an implementation, not the specification.

**Comment by Diablo-D3** [comment] 2021-05-03 06:38
Is there any way to have your build tool make entirely new weights on top of the existing ones? I don't entirely understand how it works. I'd like to have semi-light *and* regular *and* light without overwriting any others.
