### ISSUE TITLE
idea下中文字体显示出错

### ISSUE THREAD

**Issue by RicarKS** [be5invis/Iosevka#456] opened 2020-03-22 13:01 UTC
* Your font version: 3.0.0-rc.4
* Your font variant:extended
* Your operating system (name and version):windows 10 1909
* Your application using Iosevka: idea 2019.2

中文字体显示不全
![image](https://user-images.githubusercontent.com/49403030/77250049-1c062580-6c80-11ea-8bd2-cb51fe468a45.png)

**Comment by be5invis** [comment] 2020-03-22 13:14
Iosevka doesn't have far east characters.
Closed as by design.

**Closed by be5invis** 2020-03-22 13:14 UTC
