### ISSUE TITLE
Why the curly style is no longer the default?

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#452] opened 2020-03-18 08:19 UTC
This is a query, not a problem. 

I'm trying to understanding the reason for moving away from the curly style as the default.What made you switch? I personally find the curly style more attractive.

**Comment by be5invis** [comment] 2020-03-18 09:05
Since I am providing the extende width, curly variant does not work well for wider metrics. Straight is more universal.
Closed as by design.

**Closed by be5invis** 2020-03-18 09:05 UTC

**Comment by Livven** [comment] 2020-03-22 20:53
Hey, sorry to bug you about this but are you sure you want to make the default worse in order to cater to a minority?

Presumably curly used to be default because you found it better. So now you are making it worse for the majority who are going to be using the default version, and better for a minority using the extended version.

Again, sorry for being annoying, I don't want to question your judgment, just curious :) Thanks for the awesome font, been using it for a few days and switched everything over!

**Comment by IceMan81** [comment] 2020-03-23 18:13
@Livven I second that - it is an awesome font. I used to be a sworn fan of PragmataPro till I switched over to Iosevka.
I built my own with slight increase in thickness and using strong hinting settings (-a sss) for ttfautohint. If the hinting could get a bit more closer to PragmataPro it would be awesome.
