### ISSUE TITLE
Style of dots and commas in diacritical marks not synced with one for punctuation and symbols

### ISSUE THREAD

**Issue by dntzu** [be5invis/Iosevka#1180] opened 2021-07-30 13:28 UTC
The problem is already identified in the title. I think at least style of diacritic dots should be linked to chosen shape of punctuation ones. Not quite sure about commas but quick glance at the fonts specimen told me there shouldn't be much of a problem either. 

Of course I am talking about dots and commas only. More complicated diacritic marks should stay the same.

![iTtBrzXSXE](https://user-images.githubusercontent.com/34572332/127659702-26b35806-fee2-49b3-9f2a-4dccf563a730.png)

**Comment by be5invis** [comment] 2021-07-30 21:02
This is by design. See comments in #927.
Closing.

**Closed by be5invis** 2021-07-30 21:02 UTC
Labels: 🐞 Bug
