### ISSUE TITLE
npm run build -- ttf::iosevka-custom takes too long and uses 100% of cpu 

### ISSUE THREAD

**Issue by mh-firouzjaah** [be5invis/Iosevka#936] opened 2021-04-04 17:30 UTC
hi there, 
running `npm run build -- ttf::iosevka-custom` takes 100% of cpu on windows, so is it a problem or not?

**Comment by be5invis** [comment] 2021-04-04 20:27
It needs to build 54 files so it will take some time.
You can reduce the weights or slopes to reduce the family size.
On my 32-core system, it takes about 1.5 minutes.
Closing as by design.

**Closed by be5invis** 2021-04-04 20:27 UTC

**Comment by rben01** [comment] 2021-06-10 16:29
@be5invis Is there a way to limit the number of threads that the build process spawns? I'd prefer to use just one or two threads so that my computer doesn't grind to a halt while the font builds.

**Comment by alexeyten** [comment] 2021-06-10 17:21
https://github.com/be5invis/Iosevka/issues/847#issuecomment-805299137

Should work:
> `npm run build -- --jCmd=2 ttf::iosevka-custom`

**Comment by rben01** [comment] 2021-06-10 17:27
@alexeyten Thanks!

**Comment by ShimmerFairy** [comment] 2021-07-28 07:20
Please consider documenting the `--jCmd` option somewhere. Maybe it's just because I'm unfamiliar with JS development, but I had a hell of a time finding this important option. I even went so far as to try and find documentation on the verda program you seem to use under the hood, but it appears their only documentation is the terse README that comes with the package.

**Comment by alexmyczko** [comment] 2026-02-22 08:55
@be5invis can you still build it below 10 minutes? 5 years later? 

gave up on my 12core arm64 machine. and here it is an hour already: https://buildd.debian.org/status/package.php?p=fonts-iosevka&suite=experimental
