### ISSUE TITLE
Build fails on macOS El Capitan 10.11.6

### ISSUE THREAD

**Issue by geraldus** [be5invis/Iosevka#128] opened 2016-11-28 09:09 UTC
* Your font version: git HEAD
* Your operating system (name and version): macOS El Capitan 10.11.6
* Your Node.js version: v5.7.0
* Your results of `npm list`:
```
iosevka@1.9.2 …/Iosevka
├── bezier-js@2.2.1
├── cubic2quad@1.1.0
├── libspiro-js@0.3.1
├─┬ patel@0.31.4
│ ├─┬ escodegen@1.8.1
│ │ ├── esprima@2.7.3
│ │ ├── estraverse@1.9.3
│ │ ├── esutils@2.0.2
│ │ ├─┬ optionator@0.8.2
│ │ │ ├── deep-is@0.1.3
│ │ │ ├── fast-levenshtein@2.0.5
│ │ │ ├── levn@0.3.0
│ │ │ ├── prelude-ls@1.1.2
│ │ │ ├── type-check@0.3.2
│ │ │ └── wordwrap@1.0.0
│ │ └─┬ source-map@0.2.0
│ │   └── amdefine@1.0.1
│ ├─┬ esmangle@1.0.1
│ │ ├── escodegen@1.3.3
│ │ ├─┬ escope@1.0.3
│ │ │ └── estraverse@2.0.0
│ │ ├── esprima@1.1.1
│ │ ├─┬ esshorten@1.1.1
│ │ │ └── estraverse@4.1.1
│ │ ├── estraverse@1.5.1
│ │ ├── esutils@1.0.0
│ │ ├─┬ optionator@0.3.0
│ │ │ ├── fast-levenshtein@1.0.7
│ │ │ ├── levn@0.2.5
│ │ │ └── wordwrap@0.0.3
│ │ └── source-map@0.1.43
│ ├─┬ patrisika@0.21.0
│ │ └── patrisika-scopes@0.11.0
│ └─┬ resumer@0.0.0
│   └── through@2.3.8
├── toml@2.3.0
├── unorm@1.4.1
└─┬ yargs@6.4.0
  ├── camelcase@3.0.0
  ├─┬ cliui@3.2.0
  │ ├─┬ strip-ansi@3.0.1
  │ │ └── ansi-regex@2.0.0
  │ └── wrap-ansi@2.0.0
  ├── decamelize@1.2.0
  ├── get-caller-file@1.0.2
  ├─┬ os-locale@1.4.0
  │ └─┬ lcid@1.0.0
  │   └── invert-kv@1.0.0
  ├─┬ read-pkg-up@1.0.1
  │ ├─┬ find-up@1.1.2
  │ │ ├── path-exists@2.1.0
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ └─┬ read-pkg@1.1.0
  │   ├─┬ load-json-file@1.1.0
  │   │ ├── graceful-fs@4.1.11
  │   │ ├─┬ parse-json@2.2.0
  │   │ │ └─┬ error-ex@1.3.0
  │   │ │   └── is-arrayish@0.2.1
  │   │ ├── pify@2.3.0
  │   │ └─┬ strip-bom@2.0.0
  │   │   └── is-utf8@0.2.1
  │   ├─┬ normalize-package-data@2.3.5
  │   │ ├── hosted-git-info@2.1.5
  │   │ ├─┬ is-builtin-module@1.0.0
  │   │ │ └── builtin-modules@1.1.1
  │   │ ├── semver@5.3.0
  │   │ └─┬ validate-npm-package-license@3.0.1
  │   │   ├─┬ spdx-correct@1.0.2
  │   │   │ └── spdx-license-ids@1.2.2
  │   │   └── spdx-expression-parse@1.0.4
  │   └── path-type@1.1.0
  ├── require-directory@2.1.1
  ├── require-main-filename@1.0.1
  ├── set-blocking@2.0.0
  ├─┬ string-width@1.0.2
  │ ├── code-point-at@1.1.0
  │ └─┬ is-fullwidth-code-point@1.0.0
  │   └── number-is-nan@1.0.1
  ├── which-module@1.0.0
  ├── window-size@0.2.0
  ├── y18n@3.2.1
  └── yargs-parser@4.1.0
```
* Your _otfcc_ version: 0.6.2.
* Your FontForge version: FontForge version 20161003 based on sources from 23:50 PDT  3-Oct-2016 git:072edb0235cd163d6c3391da9cc3754c3c66f47a
* Your `parameters.toml`:

Here is a build log:
```
make DONTHINT=1
node ./node_modules/patel/bin/patel-c --optimize --strict support/glyph.ptl -o support/glyph.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/spiroexpand.ptl -o support/spiroexpand.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/spirokit.ptl -o support/spirokit.js
node ./node_modules/patel/bin/patel-c --optimize --strict parameters.ptl -o parameters.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/anchor.ptl -o support/anchor.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/point.ptl -o support/point.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/transform.ptl -o support/transform.js
node ./node_modules/patel/bin/patel-c --optimize --strict support/utils.ptl -o support/utils.js
node ./node_modules/patel/bin/patel-c --optimize --strict meta/aesthetics.ptl -o meta/aesthetics.js
node ./node_modules/patel/bin/patel-c --optimize --strict meta/naming.ptl -o meta/naming.js
node ./node_modules/patel/bin/patel-c --optimize --strict meta/features.ptl -o meta/features.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/common-shapes.ptl -o glyphs/common-shapes.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/overmarks.ptl -o glyphs/overmarks.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/letters-unified-basic.ptl -o glyphs/letters-unified-basic.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/letters-unified-extended.ptl -o glyphs/letters-unified-extended.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/numbers.ptl -o glyphs/numbers.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-punctuation.ptl -o glyphs/symbol-punctuation.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-math.ptl -o glyphs/symbol-math.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-letter.ptl -o glyphs/symbol-letter.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-geometric.ptl -o glyphs/symbol-geometric.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-other.ptl -o glyphs/symbol-other.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/symbol-braille.ptl -o glyphs/symbol-braille.js
node ./node_modules/patel/bin/patel-c --optimize --strict glyphs/autobuilds.ptl -o glyphs/autobuilds.js
node ./node_modules/patel/bin/patel-c --optimize --strict buildglyphs.ptl -o buildglyphs.js
/Applications/Xcode.app/Contents/Developer/usr/bin/make fonts config=d-sans
    Start building font Iosevka Thin 1.9.6 (Ingrid)
    Iosevka Thin 1.9.6 (Ingrid) Successfully built.
    Writing outline as SVG -> build/.pass0-iosevka-thin.svg
    Writing metadata as JSON -> build/.pass0-iosevka-thin.fdt
make[2]: *** [build/.pass1-iosevka-thin.ttf] Error 127
make[1]: *** [fonts] Error 2
make: *** [fonts-d-sans] Error 2
```

**Comment by be5invis** [comment] 2016-11-29 01:42
It's a dupe of #127.
It is related to FontForge, and it is considered as Mac-specific.

**Closed** 2016-11-29 01:42 UTC

**Comment by geraldus** [comment] 2016-11-29 06:14
What a pity.

**Comment by visvadw** [comment] 2016-12-01 08:12
@geraldus After trying also to build the fonts on macOS, I made the build working on a Linux Mint system. So you may grab the result from [here](https://github.com/visvadw/design-assets/tree/master/iosevka-font/iosevka-webfonts).

**Comment by visvadw** [comment] 2016-12-01 08:17
@be5invis I think it would be nice to include the [webfonts build](https://github.com/visvadw/design-assets/tree/master/iosevka-font/iosevka-webfonts) as part of the current release download options, so that less people will struggle to build them.

**Comment by geraldus** [comment] 2016-12-01 09:07
@visvadw Appreciate your help, but I'm afraid this is not what I need.  I tried to build fonts from source to get custom set of character variants.

**Comment by visvadw** [comment] 2016-12-01 10:10
@geraldus Sure, I understand. In this case, I would advice you to use a Linux system. Or, if you keep digging and find a solution on macOS, it would be nice to share it. 😄

**Comment by be5invis** [comment] 2016-12-03 11:23
@visvadw @geraldus 
You know, I really dislike FontForge, it is extremely buggy and unreliable.
The current step used FontForge removes the outline overlaps and perform “reference-ify” which massively reduces file size.
