### ISSUE TITLE
some full-width symbol appear as half-width symol

### ISSUE THREAD

**Issue by skyfire000** [be5invis/Iosevka#525] opened 2020-05-09 06:24 UTC
* Your font version: version 3.0.0-rc.8

the font chr(8220) chr(8221)  '“'  '”'   should be full width  (2-column)

**Comment by be5invis** [comment] 2020-05-09 15:45
Iosevka is not designed for Western locales. These quote symbols are narrow in their locale.
Closed as by design.

**Closed by be5invis** 2020-05-09 15:45 UTC
