### ISSUE TITLE
Segmented slash in per mille and per ten thousand signs

### ISSUE THREAD

**Issue by PHSpline** [be5invis/Iosevka#1048] opened 2021-05-23 22:55 UTC
Currently, the segmented-slash from the percent sign is not being carried across into the per mille and per ten thousand signs.  Is this intentional, or would it make sense to apply the segmented-slash to all three for consistency?  Thanks.

![image](https://user-images.githubusercontent.com/19807897/119279110-2bb82b80-bbef-11eb-8918-1cda57cd6ff8.png)

---

* Your font version: 7.0.0-preview.4
* Your font variant: Both Sans and Slab

**Comment by be5invis** [comment] 2021-05-23 23:05
This is intensional, because, well, segmenting the bar in `%` sign is considered as a compromise of limited space. Since we have more space in permille and basepoint sign, this is no longer necessary.

Closing as by design.

**Closed by be5invis** 2021-05-23 23:05 UTC
Labels: 🐞 Bug
