### ISSUE TITLE
there is no  character U+EE01

### ISSUE THREAD

**Issue by hingbong** [be5invis/Iosevka#329] opened 2019-05-12 05:50 UTC
in my use,i found a character lack which is U+EE01,which is a colon

**Comment by alexeyten** [comment] 2019-08-10 08:21
https://www.fileformat.info/info/unicode/char/ee01/index.htm

> U+EE01 is not a valid unicode character.

**Comment by be5invis** [comment] 2019-08-10 08:42
Closed as by design.
U+EE01 is a PUA character, and is not  Iosevka's goal.
(Currently the only “goal” PUA characters are Powerline.)

**Closed by be5invis** 2019-08-10 08:42 UTC
