### ISSUE TITLE
Certain arrow ligatures look misaligned at smaller font sizes 

### ISSUE THREAD

**Issue by josh-berry** [be5invis/Iosevka#550] opened 2020-05-24 07:59 UTC
* Your font version: (Release or git, version) git tag `v3.0.1`
* Your font variant: Custom settings, see below
* Your operating system (name and version): Windows 10 Pro v1909, build 18363.836
  * Using a HiDPI display at 3840x2160, with scaling set to 150% (the recommended value)
* Your application using Iosevka: Multiple, including Visual Studio Code Insiders and Windows Terminal
* Node.js version: v14.3.0
* otfcc version: v0.10.4

My customizations are as follows:

```
> diff -u private-build-plans.sample.toml private-build-plans.toml
--- private-build-plans.sample.toml     2020-05-23 21:31:09.842209492 -0700
+++ private-build-plans.toml    2020-05-23 23:41:39.175718178 -0700
@@ -1,6 +1,6 @@
 [buildPlans.iosevka-custom]               # <iosevka-custom> is your plan name
-family = "Iosevka Custom"                 # Font menu family name
-design = ["v-i-hooky", "v-l-hooky"]       # Customize styles
+family = "Iosevka Des Term"                 # Font menu family name
+design = ["sp-term", "cv24", "cv08", "cv26", "cv76", "cv61" ]       # Customize styles
 # upright = ["upright-styles"]            # Uncomment this line to set styles for upright only
 # italic = ["italic-styles"]              # Uncomment this line to set styles for italic only
 # oblique = ["oblique-styles"]            # Uncomment this line to set styles for oblique only
```

### Describe your problem here. Provide pictures and files if necessary.

I use VScode with the Iosevka font built as described above. I noticed the lines in the arrow ligatures (such as `=>`, `<-` and `->`) don't seem to line up quite right at smaller font sizes (below about 16pt or so)--the lines leading into the arrows look slightly offset up or down (depending on the font size). Also, on the double-lined arrows (e.g. `=>`), it looks like there are extra pixels hanging off the top or bottom of the arrow (again depending on font size).

I also have a Mac, and everything lines up correctly using the exact same build of Iosevka on my Mac, at any display scaling (including non-integral scalings). So it seems like this issue might be Windows-specific.

I'm attaching screenshots from VSCode on Windows at 12pt and 14pt fonts, using the same set of characters from the example on the website.

12pt:
<img width="238" alt="iosevka-ligatures-12pt" src="https://user-images.githubusercontent.com/1203893/82748504-42674080-9d57-11ea-8e27-1cf96f4d6e6b.png">

14pt:
<img width="267" alt="iosevka-ligatures-14pt" src="https://user-images.githubusercontent.com/1203893/82748501-3da28c80-9d57-11ea-8585-f47fc79029ef.png">

It's a fairly minor cosmetic thing, but wanted to raise it in case there's an easy fix. The font otherwise looks great and I'm really happy with it--thanks for making it, and especially for giving people the ability to customize it to their taste!

**Comment by be5invis** [comment] 2020-05-24 08:30
It is hint-related. You can install the **Unhinted TTF** which should not have this problem (but the text might be less clear). Again, it is beacuse that @lemzwerg's ttfautohint doesn't have any idea that these characters should be considered as "symbols with a horizontal symmetric axis".
Close as duplicate of #143.

**Closed by be5invis** 2020-05-24 08:30 UTC
Labels: 📺 Render/Hinting

**Comment by be5invis** [comment] 2020-05-24 08:31
Note: I _may_ implement some semi-automatic-hinting in next major release (4.x) but that is a long term work.
