### ISSUE TITLE
Iosevka and fontlint

### ISSUE THREAD

**Issue by jayaddison** [be5invis/Iosevka#533] opened 2020-05-19 10:09 UTC
* Your font version: (Release or git, version)
[v3.0.0](https://github.com/be5invis/Iosevka/releases/tag/v3.0.0)

* Your font variant:
Various (most recently confirmed for `iosevka-thin.ttf`)

* Your operating system (name and version):
Debian Linux (bullseye)

* Your application using Iosevka:
[`fontlint`](https://fontforge.org/docs/fontutils/fontlint.html)

Disclaimer: I'm naive about many of the workings of fonts.

I noticed that `fontlint` fails and generates a number of complaints for Iosveka v3.0.0 font files.

It's possible these are misattributed errors and could imply bugs in `fontlint` itself; either way I figured it'd be worth reporting so that either `iosveka` and/or `fontlint` can be corrected.

The majority of the error lines when running `fontlint <iosveka-font-file>` are of the form:

```
The advance width of <glyph> (500) does not match the font's advanceWidthMax (1000) and this is a fixed pitch font
```

And there are a few other specific error messages included near the tail of the output:

```
ERROR      2 Self-intersecting glyph
ERROR      3 Wrong direction
ERROR      5 Missing points at extrema
```

**Comment by be5invis** [comment] 2020-05-19 10:13
```
The advance width of <glyph> (500) does not match the font's advanceWidthMax (1000) and this is a fixed pitch font
```
This is by design since Iosevka has double-width glyphs. The `Fixed` variant should not have this.

```
ERROR      2 Self-intersecting glyph
ERROR      3 Wrong direction
ERROR      5 Missing points at extrema
```
These are mainly geometry issues — which is hard to avoid but doesn't matter in modern rasterizers.

**Comment by jayaddison** [comment] 2020-05-19 10:37
Thanks for the swift response!

I've been able to reproduce the glyph width advance errors for the [Fixed release variant](https://github.com/be5invis/Iosevka/releases/download/v3.0.0/ttf-iosevka-fixed-3.0.0.zip):

```sh
$ fontlint iosevka-fixed-medium.ttf
...
The advance width of glyph4856 (0) does not match the font's advanceWidthMax (500) and this is a fixed pitch font
```

**Comment by be5invis** [comment] 2020-05-19 17:02
```
The advance width of glyph4856 (0) does not match the font's advanceWidthMax (500) and this is a fixed pitch font
```

This is nosense! Iosevka has to support many of these combining diacritic marks, and their width *should be* 0.

**Comment by jayaddison** [comment] 2020-05-19 17:08
Ok, no problem.  I'll see whether I can take that upstream to [fontforge](https://github.com/fontforge/fontforge) as an issue there (unless you'd prefer to raise an issue with them?)

**Comment by be5invis** [comment] 2020-05-20 04:21
Closed as external.

**Closed by be5invis** 2020-05-20 04:21 UTC

**Comment by jayaddison** [comment] 2023-02-10 09:54
Raised (a few years delayed, oops) externally as fontforge/fontforge#5198.
