### ISSUE TITLE
Programming Ligatures (like in Fira Code—or PragmataPro)

### ISSUE THREAD

**Issue by Artoria2e5** [be5invis/Iosevka#56] opened 2016-01-24 05:44 UTC

**Comment by be5invis** [comment] 2016-01-24 16:13
No, unless the editor provides the current programming language through some features like `locl`'s language.

**Comment by Arthur2e5** [comment] 2016-02-15 20:23
An interesting approach to solve things like `/=` can be spotted in PragmataPro: the two glyphs are just pushed together and connected, like normal 'ligatures'.

![](http://www.fsd.it/wp-content/uploads/2015/12/PragmataPro_Haskell.png).

**Comment by be5invis** [comment] 2016-02-16 01:07
I wil consider including some "ligation" instead of ligatures: the "ligature" glyphs will be separated to 2 or three glyphs but connected when arranged togther. For example the arrow (->) will be inplemented as:

```opentype
sub hyphen' greater by dash.arrowright;
sub dash.arrowleft' greater by greater.arrowright;
```

**Comment by be5invis** [comment] 2016-02-23 19:51
In 1.8.0 I included six (experimental) ligatures ![image](https://cloud.githubusercontent.com/assets/240091/13264540/a345d1e8-daa9-11e5-8b02-f8fe79246014.png) assigned to `calt`.
The ligatures in Iosevka will not "break" the text, therefore substitutions like “change `>=` into `≥`” will not be included.

**Comment by be5invis** [comment] 2016-02-26 19:42
Current set:
![image](https://cloud.githubusercontent.com/assets/240091/13363394/148422d6-dd04-11e5-970d-955e34982567.png)

**Comment by Arthur2e5** [comment] 2016-02-26 23:24
Wow…

**Comment by sliceofcode** [comment] 2016-02-28 05:43
That looks great! :smile: If you don't mind me asking, what colorscheme is that?

**Comment by antanst** [comment] 2016-03-04 14:48
Looks great. Thank you!

**Comment by be5invis** [comment] 2016-03-04 14:52
@antanst The snapshot has ligatures for `<== <=> <==> => ==>`. It will be included in 1.8.1
Some "breaking" ligatures, like `>=`, will not be enabled by default.

**Comment by be5invis** [comment] 2016-03-05 23:02
Current Set (in `master`)
```
>>- <-< <-- <- >- <-> -< -> --> >-> -<<  <-->
>>= <=< <==       <=> =< => ==> >=> =<<  <==>```

**Comment by IceMan81** [comment] 2016-03-06 04:16
@be5invis This is cool! 
I hope I can get this working in Intellij which added some experimental support for ligatures. I saw that => works in the console but not in the editor. 
Adding the issue tracking ligature support in Intellij here for reference.
https://youtrack.jetbrains.com/issue/IDEA-127539

**Comment by Arthur2e5** [comment] 2016-03-06 04:20
@IceMan81 You may want to add a note and let IntelliJ enable `calt` too.

**Comment by msva** [comment] 2016-03-06 20:27
> Some "breaking" ligatures, e.g. Fira Code-like >=, **will not be enabled by default.**

But have you plans to make them easy to enable by user request? Say, something like `braking-ligatures` make target, or so? :)

**Comment by be5invis** [comment] 2016-03-06 23:00
@msva Perhaps assign to some separate OpenType feature, maybe ss20.

**Comment by be5invis** [comment] 2016-05-26 12:36
In the next release Iosevka will enable language-specific ligature feature names, that is, `X<extension>`. For example, `XCPP` for C++ and `XHS_` for Haskell.

**Comment by robbiemu** [comment] 2016-09-16 14:58
Some others I personally wish you guys would add some common programming ligatures:

== (as a long variant of the = sign)
!= (as ≠ sign)
=== (as a long variant of the = sign)
!== (as a slashed long = sign)
>= (the  ≥  sign)
<= (the ≤  sign)
... (as the elipses)
 (as solid line variants of the same shape)

I can get these in fira pro for example, but this font is a bit more to my liking.

**Comment by Baldrs** [comment] 2016-11-18 16:06
@robbiemu for strict equality(===/!==) operators I believe this will probably will fit better: https://en.wikipedia.org/wiki/Triple_bar

**Comment by Baldrs** [comment] 2016-11-18 16:24
@be5invis Really having this set(as seen in monoid font), in your super awesome font would be great(note: I've added strict equality sign in the screenshot manually, demo page for some reason misses it).

![image](https://cloud.githubusercontent.com/assets/814651/20437227/cfaa7960-adbb-11e6-853d-25488cd9284c.png)

     <-- ->> <<- -> <- => <=> <==> ==> <== >>= =<< -- 
    := =:= == === !== != <= >= // /** /* */ && .& || !! :: >> << 
    ¯\_(ツ)_/¯ __ ___ .. ...

**Comment by Baldrs** [comment] 2016-11-18 16:26
@IceMan81 PhpStorm 2016.3 comes with full ligature support, just have played with different fonts to see if it is so and it it working.

With your font, for example: 

![image](https://cloud.githubusercontent.com/assets/814651/20437406/8155a8ba-adbc-11e6-84f1-70bb4ced2c78.png)

**Comment by IceMan81** [comment] 2016-11-18 17:22
@Baldrs With the recent changes to Intellij and their custom JDK, ligatures work beautifully.

**Comment by Baldrs** [comment] 2016-11-22 15:44
Where to start looking on how to add a ligature?

**Comment by vikky49** [comment] 2017-03-02 19:08
This is a great font .I have been using it daily these days ..But it would be nice to have few more ligatures like == , != , >= and <= ... Any idea when these would be available ?

**Comment by be5invis** [comment] 2017-03-05 09:51
@vikky49 Breaking ligatures will be another story I think...

**Comment by mrkgnao** [comment] 2017-03-09 20:53
@be5invis is there no way to have the ligatures as custom Unicode symbols as well (like Fira Code)? That way I could write a bit of Emacs Lisp to render the ligatures with `font-lock-mode`. :)

**Comment by Ljzn** [comment] 2017-03-16 02:33
Beautiful! Thanks for your work. And I think a new pipe operator `|>` will be very nice.

**Comment by Baldrs** [comment] 2017-03-23 09:02
@be5invis i've figured out how to add ligatures that merge symbols for `==` and `===`:

![screenshot_20170323_105912](https://cloud.githubusercontent.com/assets/814651/24239751/c9845c96-0fb7-11e7-9560-123bea9697a5.png)

Couple of questions: how can I make strict equality symbol to appear instead of `===`? 
and for not equal operators, how can I make it be like this:

![screenshot_20170323_110115](https://cloud.githubusercontent.com/assets/814651/24239816/0817722c-0fb8-11e7-9a94-20a7c628326e.png)

Do I need to draw special symbols for that?

**Comment by be5invis** [comment] 2017-03-23 09:04
@Baldrs 
It looks like that your environment (some Linux I think) cannot handle Iosevka properly. I did NOT made any ligatures about `==` and `===`. Try Iosevka Term instead.

In Iosevka, `==` and `===` should look like this:
![image](https://cloud.githubusercontent.com/assets/240091/24239918/b4c1e494-0fea-11e7-8960-93e289ed6e0d.png)

**Comment by Baldrs** [comment] 2017-03-23 09:09
@be5invis I tried to made them myself, this is not bug report

**Comment by Baldrs** [comment] 2017-03-23 09:10
@be5invis #165

**Comment by be5invis** [comment] 2017-03-23 09:12
@Baldrs You need to add glyphs into it, perhaps need to check out `glyphs/symbol-math.ptl`
Also, `[equality cls]` would also introduce ligatures related to `-`. Forms like `({'equal'} ~> {'equal.fc'})` would be better.

**Comment by Baldrs** [comment] 2017-03-23 09:14
@be5invis I've added `equality` to avoid -- and --- ligation(I've exclided `hyphen`) from it's definition.

**Comment by Baldrs** [comment] 2017-03-23 09:16
@be5invis ok will take a look, thanks!

**Comment by be5invis** [comment] 2017-03-23 09:16
Definition of glyph `equal` (=) is [here](https://github.com/be5invis/Iosevka/blob/master/glyphs/symbol-math.ptl#L112).
Definition of `ident` (≡) is [here](https://github.com/be5invis/Iosevka/blob/master/glyphs/symbol-math.ptl#L340).

Perhaps you should fork these glyphs, add two suffixed version (like, `equal.eqeq_left`, `equal.eqeq_right`, `ident.eqeqeq_left`, etc). The `equal.fc` is intended to be used in ARROWS like `==>`. They does not share same spacing and weight of equal symbol.

**Comment by be5invis** [comment] 2017-03-23 09:21
And also, you may need to make some slash symbols, as the substituted form of `!`.
You may need to include your own `dispiro`s, and save to certain glyph names:

```ptl
sketch
	include : dispiro
		widths.center [adviceBlackness 4]
		flat (WIDTH + ...) (...)
		curl (WIDTH - ...) (...)
	save "slash.noteq"
```

**Comment by hauleth** [comment] 2017-04-01 12:04
If I could suggest one more ligature `|>`. In Hasklig this looks like that:

![zrzut ekranu 2017-04-01 14 03 56](https://cloud.githubusercontent.com/assets/291639/24578616/23185360-16e4-11e7-8bd5-17f943341f35.png)

**Comment by michaelmior** [comment] 2017-04-01 14:37
Curious why the term "ligation" instead of "ligature" is used in the README. I've never seen this term used anywhere with respect to typography.

**Comment by be5invis** [comment] 2017-04-01 17:38
@michaelmior Because there is actually, no “ligature” in Iosevka. 

You see a `=>`, which is actually a modified `=` and a `>`, overlapping together.

**Comment by michaelmior** [comment] 2017-04-01 21:09
@be5invis Thanks for clarifying. Personally, I would find it helpful to have a short sentence explaining this in the README.

**Comment by bluestrike2** [comment] 2017-04-02 13:46
@be5invis @michaelmior I've never seen it put in those terms, either. Except perhaps the transitive verb 'ligate', to connect two characters/glyphs with a ligature. I take it from your comment (and a quick peek at [ligation.ptl](https://github.com/be5invis/Iosevka/blob/master/meta/feature/ligation.ptl) and [symbol-other.ptl](https://github.com/be5invis/Iosevka/blob/b853887d265043ad95b801e9c4937e10ed514fc8/glyphs/symbol-other.ptl)) that you're combining/modifying two glyphs rather than referencing a separate glyph altogether (the "ligature").

Anyhow, linguistic curiosity aside, I've been using Iosevka for the past day. Previously, I was a huge fan of Fira Code. The narrower glyphs took a bit of getting used to, but I've enjoyed using it so far. One thing I would suggest is taking a look at some of the other ligatures in [Fira Code](https://github.com/tonsky/FiraCode). There are a number that are language-agnostic that might be of interest to Iosevka:

![Fira Code ligatures](https://raw.githubusercontent.com/tonsky/FiraCode/master/showcases/all_ligatures.png)

**Comment by josebalius** [comment] 2017-04-02 23:04
Has anyone used this font in VS Code with ligatures? I can't seem to get ligatures to work :/ . Specfically `!=` `!==` `==` `===`. I have `editor.fontLigatures: true` on settings, which worked for Pragmata and Fira.

**Comment by liaowang11** [comment] 2017-04-03 14:21
I have some questions:
1. what's the difference between ligature and ligation?
2. I understand that opentype specification have something about `Features`, but how can we leverage these features, in Emacs for example? I use `fc-query` a lot to inspect a font, but there's no sections about `Features`, is there any other tools to determine what features a font provide?

**Comment by nilsbecker** [comment] 2017-04-04 17:26
i've tried to compile a custom font by giving `SWFT` as one of the options but the extra 'ligations' do not show up in vim - does the editor have to do something else in order to activate them? (i was editing ocaml filetype)

**Comment by be5invis** [comment] 2017-04-04 17:28
@nilsbecker AFAIK only Atom and VSCode (with hack) can enable those custom feature tags. Sad.

**Comment by nilsbecker** [comment] 2017-04-04 17:28
hmm. the 'calt' ligations do work for me. does that not mean the others shoudl as well?

**Comment by be5invis** [comment] 2017-04-04 17:38
@nilsbecker Other are using different feature tags, your editor must support enabling them.
Currently only Atom and (patched) VSCode can do this.

**Comment by nilsbecker** [comment] 2017-04-04 18:03
ok, understood, thanks. 

fwiw, a good ligation feature set for modern OCaml would be a bit more than what is shown on the website. it should ideally include
```
:=  ->  <-  >>=  >|=  |>  a:b  a::b  :>  ==  !=  <>
```
long arrows and double arrows are not so important. `>=  <=` as comparison operators would be nice.

**Comment by mrkgnao** [comment] 2017-04-04 20:45
@be5invis this might be relevant to those trying to use Emacs with Iosevka:

https://gist.github.com/mrkgnao/49c7480e1df42405a36b7ab09fe87f3d

I can't tell you how happy the PUA glyphs have made me. :)

Can we get `~>`-like arrows any time soon? I'd actually love to start contributing more ligatures myself, especially for the `lens` operators.

**Comment by josebalius** [comment] 2017-04-04 20:51
@be5invis can you link to me the patch for vscode or what you need to do ?

**Comment by be5invis** [comment] 2017-04-05 06:23
@mrkgnao I do not made a "XALL" tag...

**Comment by be5invis** [comment] 2017-04-05 06:23
@josebalius Install `Custom CSS and JS loader`, and in your customized CSS:

```css
.editor-container[data-mode-id="haskell"] .monaco-editor { font-feature-settings: "XHS_" 1; }
.editor-container[data-mode-id="idris"] .monaco-editor { font-feature-settings: "XIDR" 1; }
.editor-container[data-mode-id="PatEL"] .monaco-editor { font-feature-settings: "XPTL" 1; }
```

**Comment by be5invis** [comment] 2017-04-05 06:30
@mrkgnao `<=` as an ARROW would be in a tag `ZALE`.

**Comment by be5invis** [comment] 2017-04-05 07:03
@hauleth 
![image](https://cloud.githubusercontent.com/assets/240091/24693631/14b138f2-1a11-11e7-9e6f-394b11b5b0e8.png)

**Comment by hauleth** [comment] 2017-04-05 09:26
@be5invis looks quite nice

**Comment by mrkgnao** [comment] 2017-04-05 12:41
@be5invis I know, I made one myself and enabled all the ligations in it. It's just to make things easier with the PUA glyphs since I find it hard to keep track of which ligations are in which feature set.

Also, what have we done to deserve you? I asked for the `|>` literally *yesterday* and it's already been committed. :heart:

**Comment by mrkgnao** [comment] 2017-04-05 12:44
Have you also added in the `~>` arrows?

**Comment by be5invis** [comment] 2017-04-05 12:45
Curly arrows are harder

发自我的 iPhone

在 2017年4月5日，20:44，Soham Chowdhury <notifications@github.com<mailto:notifications@github.com>> 写道：


Have you also added in the ~> arrows?

**Comment by cruhl** [comment] 2017-04-05 18:46
How can I enable `|>` in atom?

**Comment by cruhl** [comment] 2017-04-05 19:10
`font-feature-settings: "XELM" 1;`

^ That doesn't seem to render `|>` correctly, but `->` works...

**Comment by be5invis** [comment] 2017-04-05 19:12
@cruhl `|>` is in the default `calt`. I think it is a problem of your highlighter (which breaks `|>` into two tokens?) or Atom itself.
I can confirm that `|>` works perfectly in VSCode.

**Comment by cruhl** [comment] 2017-04-05 19:13
Strange, it seems to work with Fira Code. I'll keep trying.

**Comment by cruhl** [comment] 2017-04-05 19:38
Strange, it seems to work with Fira Code. I'll keep trying... I can confirm that atom isn't splitting the expression into two elements.

**Comment by be5invis** [comment] 2017-04-05 19:40
@cruhl Or maybe Atom's Electron cannot handle ligation corresponded to some specific letters (perhaps `|`). VSCode currently cannot center `<*>` due to Electron's outdated Chrome version.

**Comment by cruhl** [comment] 2017-04-05 19:42
Perhaps, but wouldn't Fira Code also not work if that was true?

**Comment by be5invis** [comment] 2017-04-05 19:44
@cruhl IDK. Iosevka intensively uses advanced features of OpenType including reverse substitution tables, so maybe Chrome under certain platform cannot handle them well.

**Comment by cruhl** [comment] 2017-04-05 19:46
Interesting, thanks for the replies!

**Comment by pencilcheck** [comment] 2017-04-06 08:43
In Fira Code, you would `set macligatures` in .vimrc to enable ligatures GUI. But somehow I can't get ligature to show up in my macvim.

I'm not sure what to do here.

**Comment by clayrat** [comment] 2017-04-07 00:14
May I also ask for:
* `<$>`, `<>` for all Haskell-like languages
* `<#>`, `<<<`, `>>>` for PureScript?

**Comment by brunobg** [comment] 2017-04-13 21:07
Wonderful font. I'm really looking forward to `!=`, `==`, `!==` and `===`. I like the triple bar for === and !==, makes it really easy to notice the difference.

**Comment by mrkgnao** [comment] 2017-04-14 15:26
Just wanted to put the request for `~>`-style operators out there. Something easier: how about offering symmetric `<<-` operators too, to parallel `->>` (the Clojure one)?

**Comment by flying-sheep** [comment] 2017-05-15 14:42
can you use fontconfig to enable alternative ligature sets.

in any case, i’m also waiting for comparison operators. fira code’s are perfection:

![image](https://cloud.githubusercontent.com/assets/291575/26063121/5107cc94-398d-11e7-8ff1-53060ce52deb.png)  
![image](https://cloud.githubusercontent.com/assets/291575/26063143/62331460-398d-11e7-8ac8-fc5d4475c33e.png)

**Comment by brunobg** [comment] 2017-06-20 21:37
Any updates on the comparison operators with ligatures? I really miss them!

**Comment by maxekman** [comment] 2017-09-07 08:13
I would also really like to have the `<=`, `>=` and `!=` ligatures.

**Comment by samjross** [comment] 2017-09-27 14:33
I've been looking into programming fonts again today after a long time being really happy with DejaVu Sans Mono, and of all the ones I've found, this is the best by a good margin. The letters are so *clear*.

+1 for comparison operators!

**Comment by ylluminate** [comment] 2017-10-11 20:20
The curved mono ligature approach that PragmataPro is extremely readable and very attractive:

![example](https://cl.ly/301B0n110t1D/Image%202017-10-11%20at%204.15.12%20PM.png)
![example](https://cl.ly/0s1r2r1q0V01/Image%202017-10-11%20at%204.16.33%20PM.png)
![example](https://cl.ly/410t1j162L18/Image%202017-10-11%20at%204.16.59%20PM.png)
![example](https://cl.ly/25042f3i302g/Image%202017-10-11%20at%204.19.52%20PM.png)
![example](https://cl.ly/0Y030B2a0h2n/Image%202017-10-11%20at%204.20.07%20PM.png)

**Comment by be5invis** [comment] 2017-10-11 20:24
@maxekman @flying-sheep 
Adding “breaking” ligatures like `>=` → `≥` would need a more careful consideration. Perhaps I would put them into `dlig` rather than `calt`.

**Comment by doasync** [comment] 2017-12-27 07:57
+ for comparison operators (==, !=, ===, !==)

**Comment by brunobg** [comment] 2018-01-29 19:30
I appreciate this is an open source project which you probably develop on your own free time, but it's a bit sad that such a high quality project and beautiful font hasn't solved this issue in two years, even with so many people considering it an important feature. It is such a help to have these ligatures when developing! Is there someway we can help to get this done?

**Comment by be5invis** [comment] 2018-01-29 20:00
@brunobg 
It depends on a design change: should we implement "breaking ligatures" like `<=` and `!=`. Considering in multiple programming languages, they could be assigned to different semantics.
Also, really, I do not have too much time since 2017 😞

**Comment by be5invis** [comment] 2018-01-29 20:01
@brunobg Perhaps they would be put under `dlig` rather than `calt`.

**Comment by be5invis** [comment] 2018-01-29 20:24
@brunobg Please track #249.
**I WILL MAKE THEM TOMMOROW.**

**Comment by be5invis** [comment] 2018-01-30 05:02
@brunobg @maxekman @flying-sheep @josebalius
![image](https://user-images.githubusercontent.com/240091/35548964-de2adf7e-05bd-11e8-9ab6-3d58aee4ca51.png)

**Comment by be5invis** [comment] 2018-01-30 05:09
Also, `/=` would also be transformed into `≠` in Haskell-ish languages (`XHS0`, `XIDR`, `PURS`, `XELM`)

**Comment by be5invis** [comment] 2018-01-30 05:16
@brunobg @maxekman @flying-sheep @josebalius
This modification has been checked into `master`.

**Comment by Baldrs** [comment] 2018-01-30 09:18
Oh that was unexpected

Best regards,
Arseny Lozitsky

**Comment by brunobg** [comment] 2018-01-31 19:19
So great! Thank you so much @be5invis . From the feedback in this issue you see it was very welcome :)

**Comment by flying-sheep** [comment] 2018-05-02 06:39
bad bot. @be5invis we should mark issues like this in a way so the bot doesn’t touch it.

**Comment by flying-sheep** [comment] 2018-07-31 07:52
@be5invis do you consider this fixed? if not, we should add

```yaml
exemptLabels:
  - Feature Request
  - …
```

to a `.github/stale.yml` file in this repo

**Comment by be5invis** [comment] 2018-07-31 07:55
Well the current set is pretty complete.
For new ligation reqs please move to #290.

**Closed by be5invis** 2018-07-31 07:55 UTC
Labels: OpenType, Priority 2
