### ISSUE TITLE
Urdu Support

### ISSUE THREAD

**Issue by ZAKhan** [be5invis/Iosevka#702] opened 2020-10-22 06:34 UTC
Can you please add support for urdu character set.

Regards

**Comment by be5invis** [comment] 2020-10-22 11:54
Duplicate of #320, since Urdu use Arabic script.
Note: Iosevka won't support Nastaʼlīq since the style is too different.

**Closed by be5invis** 2020-10-22 11:54 UTC
Labels: 🅰️ Character Request

**Comment by simurgh9** [comment] 2023-09-14 04:53
> Iosevka won't support Nastaʼlīq since the style is too different.

I think a better way to say this is that, nastalique by definition is variable pitch (both in x-axis and y-axis). A good arabic glyph set here should still be considered though.
