### ISSUE TITLE
More readable blackboard bold W

### ISSUE THREAD

**Issue by kauesena** [be5invis/Iosevka#884] opened 2021-02-08 14:32 UTC
I believe the readability of the character 𝕎 could be improved by letting only the first ascender (I don't know if that is the apropriate name in the case of W) be doublestruck.  The second and third lines are of math fonts which realize this character with only one of its segments as a double stroke despite not having the width constraints. 
![image](https://user-images.githubusercontent.com/30255100/107233084-f05b6d80-6a00-11eb-97a7-1cd3d8114cb4.png)
One could expect 𝕄 would offer the same difficulty in reading but I did not experience it.

**Comment by kauesena** [comment] 2021-02-08 14:40
A question: should the suggestion of redesign for some characters be marked as bug? This issue and the some of the other ones I've posted involving readability do not seem to fit any of the issue types we may choose.

**Comment by be5invis** [comment] 2021-02-09 04:29
Well Iosevka's design use two double-struck strokes in most uppercase letters so the `W` choose to use this shape for consistency. Closing as by design.

**Closed by be5invis** 2021-02-09 04:29 UTC
Labels: 🐞 Bug
