### ISSUE TITLE
6.0.0 lost some weight

### ISSUE THREAD

**Issue by efermi** [be5invis/Iosevka#964] opened 2021-04-24 12:23 UTC
Compared to 5.2.1 heavier weights look noticeably lighter and I can't say for the better. Is it intentional?
Here pictured unhinted release versions of the default build.
Left: ttf-unhinted-iosevka-fixed-5.2.1/iosevka-fixed-extendedheavy.ttf
Right: ttf-unhinted-iosevka-fixed-6.0.0/iosevka-fixed-extendedheavy.ttf
![Screenshot_20210424_150118](https://user-images.githubusercontent.com/3966555/115958220-3360b380-a50f-11eb-8626-e39bf372dd29.png)

**Comment by efermi** [comment] 2021-04-24 12:33
Regular width: not as pronounced as the Expanded. Notice also increased gaps between letters, is it related?
![Screenshot_20210424_152824](https://user-images.githubusercontent.com/3966555/115958929-41640380-a512-11eb-825c-c9a64aa4b1c2.png)

**Comment by efermi** [comment] 2021-04-24 12:41
Still noticeable on Bold:
![Screenshot_20210424_153640](https://user-images.githubusercontent.com/3966555/115959156-6c028c00-a513-11eb-9106-c77f4054889c.png)

**Comment by mfocko** [comment] 2021-04-24 12:52
we're talking about width not weight... it is also the first item in the changelog for this release :)

**Comment by efermi** [comment] 2021-04-24 13:07
@mfocko, as I understood it only the Extended subfamily should be affected by the change you mention (it is basically the change of `shape` from 576 to 600 and shouldn't affect the weight). But the weight change is noticeable and measurable across the regular-width fonts too.

**Comment by be5invis** [comment] 2021-04-24 15:01
This is considered by-design to balance width changes.

**Comment by be5invis** [comment] 2021-04-24 15:04
Also, the increased side bearings are also intensional, to make letter shapes look more consistent across weights.

**Comment by be5invis** [comment] 2021-04-24 15:05
Closing as by design

**Comment by efermi** [comment] 2021-04-24 16:23
Understood, my only gripe is that there is less visual distinction between heavier weighs now.

**Comment by be5invis** [comment] 2021-04-24 20:02
@efermi I fixed this by increasing the stroke width back a little, which should give enough distinction now.

**Closed** 2021-04-24 20:01 UTC
