### ISSUE TITLE
Z NOTATION TYPE COLON seems to have wrong params, it sits too low.

### ISSUE THREAD

**Issue by phadej** [be5invis/Iosevka#858] opened 2021-01-30 19:00 UTC
ompare Iosevka, which seems to top-justify with ordinary colon,

![Screenshot from 2021-01-30 20-50-07](https://user-images.githubusercontent.com/51087/106365247-e7053d80-633c-11eb-89e3-1f7b2e5c7e86.png)

with other fonts which seems to bottom-align, e.g. mononoki

![Screenshot from 2021-01-30 20-50-40](https://user-images.githubusercontent.com/51087/106365260-f6848680-633c-11eb-860c-ec4dbcf48d48.png)

or JuliaMono

![Screenshot from 2021-01-30 20-51-04](https://user-images.githubusercontent.com/51087/106365257-f2586900-633c-11eb-937f-520d2ba25024.png)

---

* Your font version: 5.0.0-rc1
* Your font variant: SS15-Fixed
* Your operating system (name and version): Ubuntu 18.04
* Your application using Iosevka: Emacs

**Comment by phadej** [comment] 2021-01-30 19:06
I'm not sure if it is visible

![Screenshot from 2021-01-30 21-05-29](https://user-images.githubusercontent.com/51087/106365533-ec638780-633e-11eb-9902-d03c13b9d847.png)

but I think that TYPE COLON's lower circle should not sit below comma circle, compared to ordinary comma colon where circles coincide.

**Comment by be5invis** [comment] 2021-01-31 05:26
Well their dots are aligned at the center. The actual image is:

![image](https://user-images.githubusercontent.com/240091/106375439-d2c33f80-6340-11eb-86b4-d657e321e4ea.png)

My reference is Z Notation's [official ISO document](http://standards.iso.org/ittf/PubliclyAvailableStandards/c021573_ISO_IEC_13568_2002(E).zip): the bottom ring is sit at the baseline:

![image](https://user-images.githubusercontent.com/240091/106375534-ba9ff000-6341-11eb-9f85-279458d4b20b.png)

**Comment by be5invis** [comment] 2021-01-31 05:27
Closing as by design.

**Closed by be5invis** 2021-01-31 05:27 UTC
Labels: 🐞 Bug
