### ISSUE TITLE
Consider adding ampersand character variant

### ISSUE THREAD

**Issue by OJFord** [be5invis/Iosevka#211] opened 2017-07-01 01:14 UTC
Firstly, thank you for Iosevka! It's a great font to begin with, but to be able to fine-tune characters to personal taste is amazing.

In that vein, I'd like to request a character variant for the ampersand, `&`, to appear more like an 'et' ligature (as in  e.g. Trebuchet MS) or at least more 'open' (as in e.g. [DejaVu](http://graphemica.com/&/glyphs/dejavu-sans-book)).

**Comment by be5invis** [comment] 2017-07-01 07:32
Moved into #140. Closed.

**Comment by akarzim** [comment] 2020-05-24 12:41
Issue #140 has been closed without taking into account this ampersand character variant, so I propose some variants much closer to an `Et` ligature and based on the reversed `3` and `Ƹ` characters (ezh U+01B8). Each variant is proposed without and with ligature. 

![ampersand](https://user-images.githubusercontent.com/130560/82752990-6c098180-9dc2-11ea-875f-4892db9a25b3.png)

**Comment by akarzim** [comment] 2020-05-24 12:50
FWIW I like the [BPmono](http://www.abstractfonts.com/search/bpmono) one too :)

![image](https://user-images.githubusercontent.com/130560/82754537-c8be6980-9dcd-11ea-9e9c-991b73e45004.png)

**Comment by throwaway571** [comment] 2020-05-24 21:36
@be5invis You may not have gotten this notification, because the issue is closed, so I’m tagging you. The main ampersand glyph variants are the one from Menlo with an open top loop, and the closed et-like glyph from Fira Code. I’m not sure whether the glyphs from @akarzim’s posts are readable as ampersands, especially at low sizes, but I’ll leave it to your consideration.

**Comment by AndydeCleyre** [comment] 2020-05-31 04:39
Copying over from [my comment](https://github.com/be5invis/Iosevka/issues/140#issuecomment-433632502) on the topic in the original issue:

> Here's a mockup of another `&`, based on `U+01B8` (`Latin capital letter ezh reversed`, `Ƹ`). It would maybe make more sense to base it on a rounder character, like `U+0190` (`Latin capital letter open E`, `Ɛ`).

![ƸT](https://user-images.githubusercontent.com/1787385/47606259-73e32300-d9df-11e8-96f5-f8939cef3d16.png)

And adding a similar mockup based on `U+0190` (`Latin capital letter open E`, `Ɛ`):

![ƐT](https://user-images.githubusercontent.com/1787385/83344589-d21c6a00-a2d6-11ea-820f-1a5bdb3fec5a.png)

---

I must say, that BPmono one is an attractive figure, though I might have trouble mentally accepting it as an ampersand.

**Comment by be5invis** [comment] 2020-05-31 05:53
This is the first variant that will be assigned to `CVAH` (original will be `CVAG`)

![image](https://user-images.githubusercontent.com/240091/83345475-59161600-a2c8-11ea-8ca0-86e02429c2bb.png)

**Comment by AndydeCleyre** [comment] 2020-05-31 06:42
The existing Iosevka ampersand curve is beautiful, and I think better than any of the mockups so far would be the current ampersand modified, with the top closed loop left intact, and the bottom one opened up at at the right-side exit from the top loop -- similar to @akarzim BPmono example.

I don't know exactly what should be done with the bottom right in this case, but this mockup will at least show how nice the top loop looks when detached from the right bottom:

![ampamp](https://user-images.githubusercontent.com/1787385/83346153-fa609480-a2e7-11ea-81e3-cdf2455d7b80.png)

I might go for a short capital `T` style like in my previous mockups, but I'm really not very handy with art tools, and will try to spare this thread from any future attempts on my part.

**Comment by OJFord** [comment] 2020-05-31 06:53
@be5invis Would it be possible also to have one more like an 'Ɛt' conjunct/ligature? i.e. as you posted but without the diagonal; with crossed 't' and tail?

**Comment by be5invis** [comment] 2020-05-31 06:54
@OJFord I plan to

**Comment by be5invis** [comment] 2020-05-31 08:48
Here is the third one, Fira-styled ampersand.

![image](https://user-images.githubusercontent.com/240091/83348368-b1591200-a2e0-11ea-9e0d-7d31873deb21.png)

**Comment by wimstefan** [comment] 2020-05-31 09:51
> Copying over from [my comment](https://github.com/be5invis/Iosevka/issues/140#issuecomment-433632502) on the topic in the original issue:
> 
> > Here's a mockup of another `&`, based on `U+01B8` (`Latin capital letter ezh reversed`, `Ƹ`). It would maybe make more sense to base it on a rounder character, like `U+0190` (`Latin capital letter open E`, `Ɛ`).
> 
> ![ƸT](https://user-images.githubusercontent.com/1787385/47606259-73e32300-d9df-11e8-96f5-f8939cef3d16.png)
> 
> And adding a similar mockup based on `U+0190` (`Latin capital letter open E`, `Ɛ`):
> 
> ![ƐT](https://user-images.githubusercontent.com/1787385/83344589-d21c6a00-a2d6-11ea-820f-1a5bdb3fec5a.png)
> 
> I must say, that BPmono one is an attractive figure, though I might have trouble mentally accepting it as an ampersand.

The straight top bar looks fantastic! That would go very well with the Fraktur-like Eszet (v-eszet-traditional, cv34) that I'm using already :)

**Comment by throwaway571** [comment] 2020-05-31 16:24
@be5invis I’d suggest that the bottom right of the Fira ampersand should vary along with G, and have a vertical spur when `cv91` is activated.

**Comment by AndydeCleyre** [comment] 2020-05-31 20:01
> The straight top bar looks fantastic!

I agree, it looks pretty great. Certainly better than the `Ɛ`-based one I submitted, and also IMO better than the new official ones introduced so far in this thread. So I guess it's my favorite here. 

But I think there's something beautiful not yet realized in the potential of keeping the original `&`'s top loop, if the rest can somehow make it look `et`/`ET`/`Et`-ish, and also not too much like `8`. That's tough. I guess if the top loop's intact, that's closer to a `e` than an `E`, but relative to the normal letter it's rather sideways, and the bottom is unhinged like a snake's jaw . . . Alright I know I said I'd try to spare everyone from any more of my sloppy mockups, but I'm hereby failing that goal. Here are some trying to preserve the top loop.

Inward straight:

![ampamp2](https://user-images.githubusercontent.com/1787385/83361433-f6b82680-a356-11ea-8732-da70885c0bb6.png)

Inward curved:

![ampamp3](https://user-images.githubusercontent.com/1787385/83361440-fddf3480-a356-11ea-8cf5-4a90e0653ea9.png)

Inward curved with inward hat (maybe bad because it looks like a `G`, though it's nice and more distinct from an `8` than the previous two):

![ampampG](https://user-images.githubusercontent.com/1787385/83361480-4eef2880-a357-11ea-8eac-7a39d383ace6.png)

Inward curved with centered hat (hat may be too long, and maybe it would be much better if the hat were curved to match the central curve of the glyph):

![ampampT](https://user-images.githubusercontent.com/1787385/83361517-b4dbb000-a357-11ea-9f97-9b080b6ed454.png)

Now I'll really really try not to post any more mockups here. Thank you.

**Comment by be5invis** [comment] 2020-05-31 20:07
I'd like to do this:
 * `VXAG` for current, closed ampersand;
 * `VXAH` for the open ampersand;
 * `VXAI` for the tailless `Ɛt`;
 * `VXAJ` for the tailed `Ɛt` (has a lower tail like `G` under `cv91`)
 * `VXAK` might be something unique. Not decided yet.

**Comment by wimstefan** [comment] 2020-05-31 23:08
Let's hope that the straight top bar will make it to VXAK 😉

**Comment by be5invis** [comment] 2020-06-01 09:36
![image](https://user-images.githubusercontent.com/240091/83396307-9f46a480-a3b0-11ea-96c9-dfd3d0bccc74.png)
This is the 4th.

**Comment by be5invis** [comment] 2020-06-01 10:59
And this is the fifth
![image](https://user-images.githubusercontent.com/240091/83402791-43821880-a3bc-11ea-8e9b-561c81aad946.png)

**Comment by wimstefan** [comment] 2020-06-01 13:45
I'm still hoping for the straight top bar variant ... ;-)

**Comment by akarzim** [comment] 2020-06-01 21:19
I love the fifth! (the one in the middle) This variant seems to be an excellent candidate for an elegant `&&` ligature.
However, ligation with other variants may also be possible.

**Comment by be5invis** [comment] 2020-06-02 01:34
But do we really need ligation for `&&`? Especially for VXAG and VXAH?
Again type design is not a ligature race.

**Comment by be5invis** [comment] 2020-06-02 06:00
![image](https://user-images.githubusercontent.com/240091/83484997-f012d780-a45a-11ea-87f2-01800ffc75f8.png)
And here is `VXAL`

**Comment by be5invis** [comment] 2020-06-02 06:01
Close as fixed.

**Closed by be5invis** 2020-06-02 06:01 UTC
Labels: 🔃 Variant Request

**Comment by wimstefan** [comment] 2020-06-02 09:29
This looks really fantastic!!! Thank you so much for being so cooperative and always trying to fulfill strange user requests 🙏
