### ISSUE TITLE
[question] custom build: excluding specific characters from the font set

### ISSUE THREAD

**Issue by teauxfu** [be5invis/Iosevka#1135] opened 2021-06-25 17:27 UTC
First off -- thanks for making this awesome font!

I'm looking for a way to exclude certain characters from the font for a custom build

- [x] I skimmed the section on custom builds in the readme https://github.com/be5invis/Iosevka#configuring-character-variants
- [x] I looked over the helper on the website https://typeof.net/Iosevka/customizer

I want to use Iosevka Term in my terminal, but I want to exclude some (all) emojis such as ⚡ so that they can fall back to being rendered by the system font or whatever

Is there an easy way to accomplish this?

**Comment by teauxfu** [comment] 2021-06-25 17:29
Hmm, this would probably be better tagged as Variant Request rather than Bug

**Comment by alexeyten** [comment] 2021-06-25 18:35
Could be duplicate of #930

**Closed** 2021-06-25 19:40 UTC
Labels: 🐞 Bug
