### ISSUE TITLE
Ligatures of == and === have glitch

### ISSUE THREAD

**Issue by Jeff11** [be5invis/Iosevka#799] opened 2021-01-18 17:58 UTC
Font version 4.5.0, SS14

On MacOS 11.1 with Android Studio 4.1.1 the `==` and `===` symbols have a glitch. Antialiasing setting doesn't matter.

See line 8 of the screenshot for an example of `===`

![image](https://user-images.githubusercontent.com/7838820/104949285-00160200-59bf-11eb-9d5a-edca16f84280.png)

**Comment by Jeff11** [comment] 2021-01-18 17:59
are also affected

**Comment by be5invis** [comment] 2021-01-18 23:17
Looks like rounding error. Java has some quirks on handling text metrics.

**Comment by be5invis** [comment] 2021-01-19 05:51
Resolve as duplicate of #594. It looks like JetBrains also did antialiasing wrong.
Closing.

**Closed by be5invis** 2021-01-19 05:51 UTC
Labels: 🐞 Bug
