### ISSUE TITLE
Jetbrains does not support font variants

### ISSUE THREAD

**Issue by dinhquochan** [be5invis/Iosevka#506] opened 2020-04-21 16:54 UTC
* Your font version: 3.0.0 rc 7
* Your operating system (name and version): macOS 10.15.4
* Your application using Iosevka: PhpStorm, Webstorm (Jetbrains Family)

Jetbrains does not support font variants, maybe to vote in [IDEA-92825](https://youtrack.jetbrains.com/issue/IDEA-92825).

Now, i know i can build custom font named: "Iosevka Extended" (family name, not variants). But, i want to Iosevka Extended is a family font (like Iosevka Term), and Iosevka Term Extended like that.

Thanks.

**Comment by be5invis** [comment] 2020-04-22 00:59
Extended is a **width**, not a **variant**.
JetBrains should improve their font enumeration instead of asking font designers to compromise.
Closed as by design.

**Closed by be5invis** 2020-04-22 00:59 UTC
