### ISSUE TITLE
Replacing "Envy Code R Style" SS10 with "Cascadia Style"

### ISSUE THREAD

**Issue by VladWinner** [be5invis/Iosevka#1107] opened 2021-06-01 22:10 UTC
As mentioned earlier, source font of SS10 is too unique and SS10 may be removed in a later release https://github.com/be5invis/Iosevka/issues/1065#issuecomment-848497398. I suggest leaving the reserved space and using it for Cascadia Mono/Code font Style.
Obviously, my list below is not perfect (and for sure there will be design contradictions, as in previous reports), but I'm sure that this style is closer to Iosevka in comparison with Envy Code R.
I used [this build](https://github.com/microsoft/cascadia-code/releases/tag/v2105.24) for matching.

### Cascadia Style SS10:

```
[composite.ss10]
tag = "ss10"
description = "Cascadia Style"

[composite.ss10.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-corner-serifless-hooked"
a = "double-storey-serifed"
b = "toothless-corner"
f = "flat-hook"
g = "single-storey-flat-hook-serifless"
j = "flat-hook-serifed"
l = "tailed-serifed"
r = "serifed"
t = "flat-hook-short-neck"
u = "bottom-right-serifed"
w = "straight-flat-top"
y = "straight-turn"
long-s = "flat-hook"
eszet = "longs-s-lig"
lower-alpha = "tailed-barred"
lower-iota = "tailed-serifed"
lower-lambda = "straight-turn"
cyrl-capital-u = "straight-turn"
zero = "dotted"
one = "base"
two = "straight-neck"
four = "open"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "straight-serifed"
eight = "two-circles"
nine = "open-contour"
asterisk = "penta-low"
paren = "large-contour"
number-sign = "slanted"
ampersand = "upper-open"
percent = "rings-continuous-slash"

[composite.ss10.italic]
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
a = "single-storey-earless-corner-serifed"
b = "toothless-corner-motion-serifed"
d = "toothed-serifed"
f = "serifless"
g = "single-storey-earless-corner-flat-hook"
h = "straight-top-left-serifed"
k = "cursive-top-left-serifed"
q = "earless-corner-tailed"
v = "curly"
w = "curly"
long-s = "flat-hook-tailed"
eszet = "longs-s-lig-descending"
cyrl-ef = "serifless"
cyrl-che = "tailed"
cyrl-yeri = "cursive"
cyrl-yery = "cursive"
ampersand = "flat-top"
```

**Comment by be5invis** [comment] 2021-06-02 01:52
Well, [Envy Code R style was added by... the author himself](https://github.com/be5invis/Iosevka/pull/179)! So I plan to keep it even if it cannot become an exact match.
Closing as by design.

**Closed by be5invis** 2021-06-02 01:52 UTC

**Comment by damieng** [comment] 2024-07-02 08:19
Only just came across this.

Yes, the SS10 isn't an exact match for Envy Code R as the overall type design is different. The idea is that SS10 matches the choices made in Envy Code R when it comes to things like double-story and single-story on some letters (a, g), the serif choices on i & l), plus the placement of * and _. Personally I really like the diagonal line capital A in some unreleased versions of Envy Code R I went that way...

Anyway, thanks for keeping it!
