### ISSUE TITLE
Letters in circles

### ISSUE THREAD

**Issue by marromlam** [be5invis/Iosevka#1188] opened 2021-08-08 03:41 UTC
- The requested character is...
  - [x] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [ ] Symbol
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------

I recently started using Iosevka since ligatures issues with kitty terminal were fixed. I was using Victor Mono and I set the vim mode I am currently in with N, I, V, R... in inverted circle. My problem is that with Iosevka the symbols I see are really tiny wrt. the ones I got with Victor Mono. Furthermore, if I try numbers in inverted circles, I can see them properly.

Would it be difficult to implement these symbols? Thanks!
🅐 (U+1F150) 🅑 (U+1F151)...

**Comment by be5invis** [comment] 2021-08-08 23:21
![image](https://user-images.githubusercontent.com/240091/128648604-841d79f7-9263-4866-9fbf-b39c509335f1.png)
We have wide versions of these, but maybe you are using the Term variant, then they will look small. **This is by design.**

**Comment by marromlam** [comment] 2021-08-09 00:16
Those look really nice! I am using the non Term variant (I think). I just basically use these lines in my `kitty.conf`:
```
# Iosevka font {{{

font_family      Iosevka
bold_font        Iosevka Bold
italic_font      Iosevka Italic
bold_italic_font Iosevka Bold Italic
font_features    Iosevka -calt +dlig cv93=3

adjust_line_height 2

# }}}
```
I get exactly this picture
![Screenshot 2021-08-09 at 02 14 41](https://user-images.githubusercontent.com/41004396/128649950-c9b9486c-8b4c-4582-9f47-b737bb0393c8.png)

**Comment by be5invis** [comment] 2021-08-09 01:13
So Kitty is shrinking the glyph :( 
I think you may report this bug to Kitty, the glyph is correct, but it made it small.

**Comment by wimstefan** [comment] 2021-08-09 11:01
Not sure if kitty is shrinking the glyph since it's behaving well with a different font - in this case Cascadia Code. Or maybe I'm just thinking too simple ... ;)

![scrot-2021-08-09-12:56_000](https://user-images.githubusercontent.com/4605934/128696590-ce09e4a7-a2d0-452c-8a2e-0a79811e7fe4.png)
![scrot-2021-08-09-12:56](https://user-images.githubusercontent.com/4605934/128696592-0424a7c2-6d99-4967-93ba-95bb4d604bb8.png)

**Comment by clsn** [comment] 2021-08-13 18:56
I noticed a while ago that kitty seems to shrink glyphs that are too big for its character cells.  This can be a problem for ligaturing fonts etc.
Maybe it isn't always happening, maybe there are different circumstances that cause it to happen or not, but I definitely know that kitty shrinks glyphs.

**Comment by be5invis** [comment] 2021-08-20 06:50
As the "enclosed letter - space" ligature is implemented in Kitty, closing this issue.

**Closed by be5invis** 2021-08-20 06:50 UTC
Labels: 🅰️ Character Request
