### ISSUE TITLE
Build fails with "TypeError: Cannot redefine property: default"

### ISSUE THREAD

**Issue by cole-h** [be5invis/Iosevka#528] opened 2020-05-13 17:39 UTC
* Your font version: every version from at least 2.0.0 onward exhibits this behavior for me (including the release candidates)
* Your font variant: N/A
* Your operating system (name and version): Arch Linux
* Your application using Iosevka: N/A

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 14.2.0-1
* Your _otfcc_ version: 0.10.4-1

* The detailed error log:
```
> iosevka@2.3.3 build /home/cole/workspace/vcs/Iosevka-2.3.3
> verda -f verdafile.js "ttf::iosevka"

/home/cole/workspace/vcs/Iosevka-2.3.3/node_modules/verda/node_modules/tslib/tslib.js:237
        Object.defineProperty(o, "default", { enumerable: true, value: v });
               ^

TypeError: Cannot redefine property: default
    at Function.defineProperty (<anonymous>)
    at /home/cole/workspace/vcs/Iosevka-2.3.3/node_modules/verda/node_modules/tslib/tslib.js:237:16
    at Object.__importStar (/home/cole/workspace/vcs/Iosevka-2.3.3/node_modules/verda/node_modules/tslib/tslib.js:246:9)
    at Object.<anonymous> (/home/cole/workspace/vcs/Iosevka-2.3.3/node_modules/verda/lib/cli/verda.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iosevka@2.3.3 build: `verda -f verdafile.js "ttf::iosevka"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iosevka@2.3.3 build script.
```

and

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--',
1 verbose cli   'ttf::iosevka'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle iosevka@2.3.3~prebuild: iosevka@2.3.3
6 info lifecycle iosevka@2.3.3~build: iosevka@2.3.3
7 verbose lifecycle iosevka@2.3.3~build: unsafe-perm in lifecycle true
8 verbose lifecycle iosevka@2.3.3~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/cole/workspace/vcs/Iosevka-2.3.3/node_modules/.bin:/home/cole/.cargo/bin:/opt/devkitpro/tools/bin:/home/cole/.local/bin/:/home/cole/.go/bin:/home/cole/.nix-profile/bin:/nix/store/1nb7q0wm97hw5zaz442vxkwg6yfh9sll-swaybg-a8f109af90353369e7e2e689efe8ce06eb9c60ac/bin:/home/cole/.nix-profile/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle iosevka@2.3.3~build: CWD: /home/cole/workspace/vcs/Iosevka-2.3.3
10 silly lifecycle iosevka@2.3.3~build: Args: [ '-c', 'verda -f verdafile.js "ttf::iosevka"' ]
11 silly lifecycle iosevka@2.3.3~build: Returned: code: 1  signal: null
12 info lifecycle iosevka@2.3.3~build: Failed to exec build script
13 verbose stack Error: iosevka@2.3.3 build: `verda -f verdafile.js "ttf::iosevka"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid iosevka@2.3.3
15 verbose cwd /home/cole/workspace/vcs/Iosevka-2.3.3
16 verbose Linux 5.6.10-zen1-1-zen
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--" "ttf::iosevka"
18 verbose node v14.2.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error iosevka@2.3.3 build: `verda -f verdafile.js "ttf::iosevka"`
22 error Exit status 1
23 error Failed at the iosevka@2.3.3 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
---

Maybe I'm missing something? I have `ttfautohint`, `otfcc`, and `otf2otc`. All I'm doing is:

1. `npm install`
2. `npm run build -- ttf::iosevka`
3. Observe the above error

Any help would be appreciated.

**Comment by be5invis** [comment] 2020-05-13 19:37
Should be a dupe of this: https://github.com/be5invis/Iosevka/issues/528

**Closed by be5invis** 2020-05-13 19:37 UTC

**Comment by cole-h** [comment] 2020-05-13 19:47
That is indeed the problem -- manually changing `node_modules/verda/package.json` to have a tslib version bound of `=1.11.1` (and removing `node_modules/tslib`) and I can build again. Is there any way you could make this change in verda and publish a new release, at least until that issue is resolved?

In any case, thanks for the link. I had Googled the issue but was unable to find anything (maybe because the issue is relatively new).

**Comment by be5invis** [comment] 2020-05-13 19:58
@cole-h `tslib` plans to publish a version `1.13.0` soon to fix this.

**Comment by be5invis** [comment] 2020-05-13 19:58
https://github.com/microsoft/tslib/pull/109

**Comment by cole-h** [comment] 2020-05-13 19:59
Beautiful, I guess I can wait until that gets merged. Thanks!
