### ISSUE TITLE
Remove default character variations from variation list

### ISSUE THREAD

**Issue by Otemachi** [be5invis/Iosevka#492] opened 2020-04-13 06:08 UTC
It's inefficient and confusing.
eg. cv01 is the double-story lowercase a (default glyph) and cv02 is the single-story lowercase a.
Remove cv01 and put cv02 in the cv01 slot.

**Comment by be5invis** [comment] 2020-04-13 07:48
The font builder could customize their build, so keeping these CV tags can create a much clearer semantics of each CV tag.
Closed as by design.

**Closed by be5invis** 2020-04-13 07:48 UTC
