### ISSUE TITLE
Not all cvxx for diagonal tails are being applied

### ISSUE THREAD

**Issue by berrymot** [be5invis/Iosevka#2009] opened 2023-09-27 19:40 UTC
In my evil quest to have all the diagonal tails, I've noticed that some of them do nothing.

![image](https://github.com/be5invis/Iosevka/assets/50974538/c924e940-65a6-42dd-b716-6d663a38c41e)

* **cv59, cv65, cv52**: only 1 has any effect
* **cv44, cv51**: all values do nothing

---

* Your font version: release 27.0.2
* Your font variant: default everything (ttf-iosevka-27.0.2.zip)
* Your operating system (name and version): Windows 11 Pro 22H2
* Your application using Iosevka: Visual Studio Code

**Comment by jmcwilliams403** [comment] 2023-09-27 20:33
This appears to be an issue with the limitations of your editor accepting a finite amount of font feature arguments.
Here's what happens if I try to access all the variants you currently want at once versus only the last three:
![image](https://github.com/be5invis/Iosevka/assets/37010132/5c5d02c2-afa2-4582-babd-d3712f93e1c6)

**Comment by berrymot** [comment] 2023-09-27 20:39
hm. how the heck can i get around this

**Comment by pv4** [comment] 2023-09-27 21:00
> an issue with the limitations of your editor accepting a finite amount of font feature arguments

IIRC harfbuzz (I tested 3.2) had this issue. It allocates 32 bits (or 64, I don't remember the exact number) to contain ALL the features to apply. E.g. currently A has 8 variants (3 bits), B has 12 variants (4 bits), so if you apply these both feature tags 7 bits are spent and 25 (or 57?) bits left for the remaining features. The features there appears to be no "space" for are just ignored. This can be easily reproduced with hb-view (or whatever it's called). Looks like an optimization/vs/correctness strategic decision.

@berrymot I see two solutions:
1. try to shorten the list of features you need so that their total size is small enough to fit the allocated bits; be prepared that that will be a really short list
2. build you own version of iosevka from source.

By the way, what set of features exactly you try to use?

**Comment by be5invis** [comment] 2023-09-27 21:12
Old Harfbuzz bug. I reported it earlier myself but they closed it as wontfix.
Resolve as external.

**Closed by be5invis** 2023-09-27 21:12 UTC
Labels: 🐞 Bug
