### ISSUE TITLE
The ligatures for `<=` and `>=` are always enabled even if `'VRLG' on` is set

### ISSUE THREAD

**Issue by rhenescu** [be5invis/Iosevka#1864] opened 2023-07-23 00:12 UTC
* Your font version: 21.0.0+
* Your font variant: Iosevka Term Curly, Iosevka Term
* Your operating system (name and version): Linux Mint 21.2, Windows 10
* Your application using Iosevka: VS Code

---

Since release 21.0.0 / fd8d7ad, the ligatures for  `<=`  and `>=` are always enabled even if `'VRLG' on` is set in VS Code's settings.json. This particularly affects how assignments are displayed in Verilog, SystemVerilog, or VHDL code, as shown below.

20.0.0 and older (correct):
![image](https://github.com/be5invis/Iosevka/assets/6264315/032123cd-52d2-45f5-bf3a-ddf103c79ea8)

21.0.0 and newer (incorrect):
![image](https://github.com/be5invis/Iosevka/assets/6264315/3688c0be-f249-4b7e-b7ef-a3e103f095d1)

**Comment by be5invis** [comment] 2023-07-23 01:04
Well, I did a query and found that [Verilog also have `<=` and `>=` as comparison operators](https://class.ece.uw.edu/cadta/verilog/operators.html), so I added them back.
Resolve as by design.

**Comment by rhenescu** [comment] 2023-07-23 14:23
Verilog, SystemVerilog, and VHDL all use `<=` both as a comparison operator (`≤`) and for assignments (`⇐`). In many cases, assignments are more common that comparisons (random example: https://github.com/ultraembedded/riscv/blob/master/core/riscv/riscv_fetch.v).

I am not aware of any working solution that selects the correct ligature depending on the context. Even if the grammar is altered to extract `<` and `=` as two separate tokens, they are still combined to form a ligature.

Displaying `ready ≤ fill_level ≤ max;` instead of `ready ⇐ fill_level ≤ max;` or `ready <= fill_level <= max;` is really confusing and enforcing either `≤` or `⇐` everywhere defeats the whole purpose of having a separate VRLG mode.

**Comment by rhenescu** [comment] 2023-07-23 14:31
For now, the only option is to stick with 20.0.0.

See also:
- https://github.com/tonsky/FiraCode/issues/696
- https://github.com/tonsky/FiraCode/issues/858

**Comment by be5invis** [comment] 2023-07-23 18:36
Got it. Fixed in dev.

**Closed by be5invis** 2023-07-23 18:36 UTC
Labels: 🐞 Bug

**Comment by rhenescu** [comment] 2023-07-29 03:35
Thank you, much appreciated!
