### ISSUE TITLE
Arrow ligatures

### ISSUE THREAD

**Issue by liangjingkanji** [be5invis/Iosevka#1193] opened 2021-08-16 01:21 UTC
- [ ] A programming language requires this ligation. Provide the information below.
- [ ] This ligation is implemented in other programming fonts. Provide samples below.

JetBrains Mono
![image](https://user-images.githubusercontent.com/21078112/129499396-ada07138-72ab-4018-ae66-b3e6243eec7b.png)

Iosevka
![image](https://user-images.githubusercontent.com/21078112/129499435-955d4ce0-0436-4c98-8ec0-de00c907c61d.png)

------

*Please provide justification here.*

His arrows are more beautiful, Iosveka of arrow looks very rough

**Comment by be5invis** [comment] 2021-08-16 03:07
The arrow is actually built with the **original** less/greater sign and the rod, so it is impossible to implement "wide" arrows. This is a part of the design system.
Closing as by design.

**Closed by be5invis** 2021-08-16 03:07 UTC
Labels: 🖇️ Ligation Request
