### ISSUE TITLE
pyftsubset broken for Iosevka 3.0.0-rc7 U+003F

### ISSUE THREAD

**Issue by jaens** [be5invis/Iosevka#502] opened 2020-04-19 00:46 UTC
Looks very similar to #348...

The last version I can successfully subset is 2.3.2.

```
iosevka-ss08-3.0.0-rc.7/ttf $ pyftsubset --unicodes=U+003F --verbose iosevka-ss08-medium.ttf

Text: ''
Unicodes: [63]
Glyphs: []
Gids: []
maxp pruned
cmap pruned
post pruned
GPOS pruned
GSUB pruned
name pruned
glyf pruned
Added gid0 to subset
Closing glyph list over 'GSUB': 2 glyphs before
Glyph names: ['.notdef', 'question']
Glyph IDs:   [0, 33]
Traceback (most recent call last):
  File "/usr/bin/pyftsubset", line 11, in <module>
    load_entry_point('fonttools==4.7.0', 'console_scripts', 'pyftsubset')()
  File "/usr/lib/python3/dist-packages/fontTools/misc/loggingTools.py", line 367, in wrapper
    return func(*args, **kwds)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 2891, in main
    subsetter.subset(font)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 2693, in subset
    self._closure_glyphs(font)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 2547, in _closure_glyphs
    font['GSUB'].closure_glyphs(self)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 1434, in closure_glyphs
    self.table.LookupList.Lookup[i].closure_glyphs(s)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 1183, in closure_glyphs
    st.closure_glyphs(s, cur_glyphs)
  File "/usr/lib/python3/dist-packages/fontTools/subset/__init__.py", line 990, in closure_glyphs
    pos_glyphs = frozenset(r.InputCoverage[seqi].intersect_glyphs(s.glyphs))
  File "/usr/lib/python3/dist-packages/fontTools/ttLib/tables/otBase.py", line 548, in __getattr__
    raise AttributeError(attr)
AttributeError: InputCoverage
```

**Comment by be5invis** [comment] 2020-04-19 02:56
It looks like `pyftsubset` cannot properly handle Iosevka, while it is completely valid (verified by [`ots`](https://github.com/khaledhosny/ots)).
A workaround may be to use `ttx` to do a roundtrip, which will please `fonttools`.

**Comment by be5invis** [comment] 2020-04-19 03:13
I can confirm it is a bug in fonttools.
Opened https://github.com/fonttools/fonttools/issues/1879.
Closed as external.

**Closed by be5invis** 2020-04-19 03:13 UTC
Labels: External
