### ISSUE TITLE
Ligatures working in Hyper terminal

### ISSUE THREAD

**Issue by dixius99** [be5invis/Iosevka#1218] opened 2021-09-09 19:42 UTC
This is more a question vs. an issue (which is why I didn't use a template).

I opened an [issue](https://github.com/vercel/hyper/issues/5928) for the [Hyper](https://github.com/vercel/hyper) terminal project about ligatures not displaying correctly when using Iosevka, while other fonts like JetBrains Mono and Fira code both seem to work as expected.

The response I got there is that this is likely an issue with Iosevka, vs. Hyper.

I tested out various past versions of Iosevka, and none seem to work for me.

Do you think that it's a problem with Iosevka? If so, I can open an issue.

**Comment by be5invis** [comment] 2021-09-10 06:46
The problem is that the `font-ligatures` package doesn't support [GSUB Extension Substitution](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub#lookuptype-7-extension-substitution), which IS a part of OT spec. Fonts with large lookups -- like Iosevka -- will have that.
Closing as external.

**Closed by be5invis** 2021-09-10 06:46 UTC
