### ISSUE TITLE
[Character Request] Double-struck letters

### ISSUE THREAD

**Issue by MithicSpirit** [be5invis/Iosevka#712] opened 2020-11-03 03:03 UTC
- The requested character is...
  - [ ] Latin
  - [ ] Cyrillic
  - [ ] Greek
  - [ ] Punctuation
  - [x] Symbol
- [ ] Some other monospace/programming fonts supported this character. Provide images below.

------

*Please provide justification here.*

Some additional ligature features, (like `:ui (ligatures +extra)` in [Doom Emacs](https://github.com/hlissner/doom-emacs/tree/develop/modules/ui/ligatures), utilize other double-struck letters to signify variable types, like `ℝ` (R) for floats (in Iosevka) and `𝕊` (S) for strings (_not_ in Iosevka).

Here is a list of all double-struck letters used in the Doom Emacs module: `𝕋` (T), `𝔽` (F), `ℤ` (Z), `ℝ` (R), `𝕊` (S), `𝔹` (B), `𝕃` (L); personally, these are the only ones I really care about, but it might be nice to just finish the entire set ¯\\\_(ツ)_/¯

**Comment by be5invis** [comment] 2020-11-03 04:35
Dupe of #444. Closed.

**Closed by be5invis** 2020-11-03 04:35 UTC
Labels: 🅰️ Character Request

**Comment by be5invis** [comment] 2020-11-03 04:37
Please note that, this is a **significant amount of work**, and since Mathematical Alphanumeric Symbols has other styled letters, there may need some building system work too.
