### ISSUE TITLE
Problem with `==` ligature

### ISSUE THREAD

**Issue by xy-ren** [be5invis/Iosevka#639] opened 2020-07-24 14:22 UTC
In this sentence (Iosevka, 19.2px):

<img width="762" alt="截屏2020-07-24 下午10 10 33" src="https://user-images.githubusercontent.com/25559236/88400809-71536e80-cdfb-11ea-9851-0bdfa61762ff.png">

the ligature of `==` has a "taller" part in the middle:

<img width="552" alt="截屏2020-07-24 下午10 18 02" src="https://user-images.githubusercontent.com/25559236/88400882-8c25e300-cdfb-11ea-9e23-52e33dd02827.png">

and this still exists in higher resolution.

---

* Your font version: v3.3.1
* Your font variant: Iosevka
* Your operating system (name and version): macOS Catalina (v10.15.5)
* Your application using Iosevka: Google Chrome

**Comment by be5invis** [comment] 2020-07-24 19:23
Dupe of #594. Closed as by design.

> Another victim of per-glyph transparency...
> This is by design. A slight overlap between joining glyphs is necessary to prevent characters from being separated when the width/height is rounded. Therefore, the transparency of text should be implemented in a _per-run_ basis, rather than _per-glyph_. W3C's ALREQ has a [great sample](https://www.w3.org/TR/alreq/#h_joining_and_transparency) of how transparency should be implemented.
> 
> ![](https://www.w3.org/TR/alreq/images/joining-and-transparency.svg)

**Closed by be5invis** 2020-07-24 19:23 UTC
Labels: 🐞 Bug
