### ISSUE TITLE
After an upgrade characters 'm' and 'w' are not sharp, when small font size (11) is selected.

### ISSUE THREAD

**Issue by Izorkin** [be5invis/Iosevka#557] opened 2020-05-27 10:29 UTC
* Your font version: v2.3.0
* Your font variant: Term Condensed customized
* Your operating system (name and version): Windows 10
* Your application using Iosevka: kitty, total commander

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: v10.20.1
* Your _otfcc_ version: 0.10.4
* Your `parameters.toml`, paste if modified:
```
diff --git a/parameters.toml b/parameters.toml
index e9f83c87..ef495bad 100644
--- a/parameters.toml
+++ b/parameters.toml
@@ -5,17 +5,17 @@ manufacturer = 'Belleve Invis'
 designer = 'Belleve Invis'
 description = 'Spatial efficient monospace font family for programming. Built from code. http://be5invis.github.io/Iosevka'

-leading = 1250     # Default line height times 1000.
+leading = 1000     # Default line height times 1000.
 descenderPad = 65  # Additional line height, added to descender.
-width = 500        # Character width. Increase this if you think that Iosevka is too narrow.
-cap = 735          # Cap height (as well as ascender).
+width = 458        # Character width. Increase this if you think that Iosevka is too narrow.
+cap = 700          # Cap height (as well as ascender).
 xheight = 530      # X-height.
 #descender = -205  # Depth of descender. Currently unused.
 winMetricPad = 0   # Padding of Win metrics to avoid clipping. See #343

-ideoMid  = 365
-symbolMid = 365    # Center of parens, maths, geometrics...
-parenSize = 1066   # Size of parens, brackets, braces, slashes, etc.
+ideoMid  = 330
+symbolMid = 330    # Center of parens, maths, geometrics...
+parenSize = 842    # Size of parens, brackets, braces, slashes, etc.
 operSize = 852     # Size of "taller" mathematical operators (cups, etc.)
 tackSize = 800     # Size of logical operators (tacks, etc.)

```
* Your `private-build-plans.toml`, if present:
```
[buildPlans.iosevka-ss00-cond]
family = "Iosevka SS00 Condensed"
design = [
  "leading-1000", "powerline-scale-x-1000", "powerline-scale-y-1000",
  "cv01", "cv04", "cv08", "cv11", "cv20", "cv25", "cv27", "cv32", "cv36", "cv39", "cv43", "cv44", "cv46", "cv51", "cv52", "cv61"
]

[buildPlans.iosevka-ss00-term-cond]
family = "Iosevka SS00 Term Condensed"
design = [
  "term",
  "leading-1000", "powerline-scale-x-1000", "powerline-scale-y-1000",
  "cv01", "cv04", "cv08", "cv11", "cv20", "cv25", "cv27", "cv32", "cv36", "cv39", "cv43", "cv44", "cv46", "cv51", "cv52", "cv61"
]

[buildPlans.iosevka-ss00-cond.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-ss00-cond.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-ss00-cond.weights.medium]
shape = 500
menu  = 500
css   = 500

[buildPlans.iosevka-ss00-term-cond.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-ss00-term-cond.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-ss00-term-cond.weights.medium]
shape = 500
menu  = 500
css   = 500
```
---

After an upgrade characters 'm' and 'w' are not sharp, when small font size is selected.
The problem was first observed after upgrade to version 2.3.0, namely after the 120e2b3d53ccf10d8cb6306d0132317ef7daa231 change
Before
![TOTALCMD64_2020-05-27_12-45-17](https://user-images.githubusercontent.com/26877687/83006262-9eadb700-a01a-11ea-88a2-ffad245bda3c.png)
After
![TOTALCMD64_2020-05-27_12-46-08](https://user-images.githubusercontent.com/26877687/83006318-b8e79500-a01a-11ea-8b0e-caa72bb3be82.png)
In version 3.0.1 problem with character 'r'.
![ShareX_2020-05-27_13-28-07](https://user-images.githubusercontent.com/26877687/83008519-f4379300-a01d-11ea-833e-e76c01d6a8f0.png)

**Comment by GTMxCode** [comment] 2020-06-06 10:35
I'm not be5invis but I think it's probably more to do with ttfautohint. Those letters and the way the stroke adjustment is calculated were definitely altered, but this was likely done to affect the way the font looks in general for most sizes, but as a side effect it messed up your particular size. 
That change is pretty old at this point but one thing of note is that the parameter 'adviceblackness' was added along with gendivframe which directly affects stroke calculation.

You can try messing with that value at risk of screwing other letters up, it's in meta/aesthetics.ptl, OR, I don't know if you've played around with ttfautohints parameters, but you could try 'qqq' instead of 'sss' and see if that helps. It's the less aggressive setting.

Also on that note if you're referencing that iosevka update that's so old it's possible that your ttfautohint also updated to a new version and THAT is the cause of your problem.. 

Hope this helps some

**Comment by Izorkin** [comment] 2020-06-06 11:59
Thanks for response.
Varint with `hintParams = ["-a", "qqq"]` does not help.
With latest ttfautohints and iosevka v2.3.0 custom building.

**Comment by be5invis** [comment] 2020-06-06 19:36
I'd like to close this. The description is about that in the older version, the vertical strokes of `m` and `w` is _coincidentally_ aligned to pixel boundary, and the property is lost in later updates.
To provide a proper fix of this we need to either do _X-hinting_, which is not supported by any of the automated hinting systems, or implement optical sizes (therefore divide Iosevka into "Iosevka" and "Iosevka Display", etc.). Considering the code-generated nature of Iosevka the latter approach is more doable.
I will open an issue for 4.0 about optical sizes.

**Closed by be5invis** 2020-06-06 19:36 UTC
