### ISSUE TITLE
Should slab dollar/cent glyphs have serifs?

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#881] opened 2021-02-06 20:27 UTC
I've just noticed serifs in slab style of `dollar`/`cent` glyphs (inherited from latin `s`/`c` I suppose). Is it an expected behaviour?

Please, do NOT introduce new variants for dollar/cent as a fix for this issue unless YOU think it matters. I can live with any variant. This issue is just an attention note in case if you have done this accidently and if you would like `dollar`/`cent` glyphs not to have serifs in slab style.

Feel free to just close this issue without any action.

**Comment by be5invis** [comment] 2021-02-06 20:36
They follow `S` and `c` wo this is by design.
Closing.

**Closed by be5invis** 2021-02-06 20:36 UTC
Labels: 🐞 Bug
